add singleton in glossary
directus/docs pull request #142
Opened 2022-09-16 07:26 UTC by anlexN

2022-09-16 08:03 UTC, br41nslug requested changes
Thanks for the PR, just that little change and we should be all set 👍

2022-09-18 03:59 UTC, anlexN commented
![image](https://user-images.githubusercontent.com/8686739/190885065-ab6ce780-6b13-47cd-bc1a-e1dde9e959bd.png)

2022-09-19 09:17 UTC, br41nslug requested changes
Checked some grammar and capitalization if you could fix those that would be great 😄

2022-09-19 09:17 UTC, br41nslug commented on getting-started/glossary.md
> +- **directus** - A collection that only contains one single item
```suggestion
- **Directus** - A collection that only contains one single item
```

2022-09-19 09:17 UTC, br41nslug commented on getting-started/glossary.md
> +- [Singleton Pattern](https://www.patterns.dev/posts/singleton-pattern/)
```suggestion
- [**Design pattern**](https://www.patterns.dev/posts/singleton-pattern/) - Classes which can be instantiated once and can be accessed globally. This single instance can be shared throughout our application, which makes singletons great for managing global state in an application.
```
The link to github seems a bit much to me for the glossary and should really be over at the JS SDK section.

2022-09-19 14:38 UTC, br41nslug approved these changes

2022-09-19 14:39 UTC, merged

2022-09-19 14:44 UTC, anlexN commented
good job