Cookbooks
directus/docs pull request #197
Opened 2022-10-28 20:53 UTC by erondpowell

A new addition to docs land.
The cookbooks help you get cookin' with Directus!
(Resolves #99 *and beyond!*)

TODO:
- [ ] Fix the dual sidebar issue
- [ ] Finalize the initial cookbook structure
- [ ] Create the first recipe for Flows
- [ ] from the first recipe, create the initial "style template"
- [ ] Define key meta-data
- [ ] Come up with more recipes
- [ ] Proofedits
- [ ] Release!

2022-11-10 20:41 UTC, AlexGaillard reviewed
Here you go @erondpowell, I made a few edits to the recipe for recipes.

2022-11-10 20:41 UTC, AlexGaillard commented on cookbook/add-a-recipe.md
> +What you're reading right now _is the recipe on how to write recipes_. It was written using the same template we use to
```suggestion
What you're reading right now _is the recipe for how to write recipes_. It was written using the same template we use to
```

2022-11-10 20:41 UTC, AlexGaillard commented on cookbook/add-a-recipe.md
> +write all other recipes. By the end, you'll know how to develop, purpose, write, and submit your recipes to the
```suggestion
write all the other recipes in our cookbook. By the end, you'll know how to develop, propose, write, and submit your recipes
```

2022-11-10 20:41 UTC, AlexGaillard commented on cookbook/add-a-recipe.md
> +  readers for what they get from your recipe. The goal is that before your readers even begin the
```suggestion
  readers for what they will get from your recipe. The goal is that before your readers even begin the
```

2022-11-10 20:41 UTC, AlexGaillard commented on cookbook/add-a-recipe.md
> +  loose-ends or answer any questions that would be harder to address in the previous two sections, when the reader isn't
```suggestion
  loose-ends or answer any questions not addressed in the previous two sections. For example, concepts that are harder
```

2022-11-10 20:41 UTC, AlexGaillard commented on cookbook/add-a-recipe.md
> +  100% sure about the details of your recipe.
```suggestion
  to explain or certain details that the user might not be 100% clear about.
```

2022-11-10 20:41 UTC, AlexGaillard commented on cookbook/add-a-recipe.md
> +First we need to confirm your recipe is a viable candidate.
```suggestion
Firstly, we need to confirm that your recipe is a viable and original candidate.
```

2022-11-10 20:41 UTC, AlexGaillard commented on cookbook/add-a-recipe.md
> +If the cookbook were filled with dozens of recipes showing how to do the exact same thing, it would be a cumbersome
```suggestion
If the cookbook were filled with dozens of similar recipes showing how to do the exact same thing, it would be a cumbersome
```

2022-11-10 20:41 UTC, AlexGaillard commented on cookbook/add-a-recipe.md
> +developer experience. Additionally, one's recipe might actually be an inefficient or dangerous way to handle something.
```suggestion
developer experience. Additionally, a recipe might actually be an inefficient or dangerous way to handle
something.
```

2022-11-10 20:41 UTC, AlexGaillard commented on cookbook/add-a-recipe.md
> +From here, a Directus Core team member will review and reply on the issue. We'll likely have questions or suggestions to
```suggestion
From here, a Directus Core team member will review it and reply directly on the issue. We will likely have questions or suggestions to
```

2022-11-10 20:41 UTC, AlexGaillard commented on cookbook/add-a-recipe.md
> +its a viable recipe together.
```suggestion
it's a viable recipe together.
```

2022-11-10 20:41 UTC, AlexGaillard commented on cookbook/add-a-recipe.md
> +By structuring your recipe properly, you provide a more consistent experience for your readers. It'll also reduce the
```suggestion
By structuring your recipe correctly, you will provide a more consistent experience for your readers. It will also reduce the
```

2022-11-10 20:41 UTC, AlexGaillard commented on cookbook/add-a-recipe.md
> +chance Directus Core team asks for edits before merging.
```suggestion
chances that the Directus Core team will ask for edits before merging.
```

2022-11-10 20:41 UTC, AlexGaillard commented on cookbook/add-a-recipe.md
> +If your recipe is similar to another existing recipe, its probably in one of three categories:
```suggestion
If your recipe is similar to another existing recipe, it's probably in one of three categories:
```

2022-11-10 20:41 UTC, AlexGaillard commented on cookbook/add-a-recipe.md
> +- Its a 1:1 mapping of an existing recipe _(perhaps with different naming conventions)_.
```suggestion
- It's a 1:1 mapping of an existing recipe _(perhaps with different naming conventions)_.
```

2022-11-10 20:41 UTC, AlexGaillard commented on cookbook/add-a-recipe.md
> +- Its a superset or a subset of an existing recipe.
```suggestion
- It's a superset or a subset of an existing recipe.
```

2022-11-10 20:41 UTC, AlexGaillard commented on cookbook/add-a-recipe.md
> +consideration. In the other two cases, your recipe may need to be modified, but its much more likely _(but not certain)_
```suggestion
consideration. In the other two cases, your recipe may need to be modified, but it's much more likely _(but not certain)_
```

2022-11-10 20:41 UTC, AlexGaillard commented on cookbook/add-a-recipe.md
> +We created this template is to provide a clear scope and style for all recipes. This makes things easier and more
```suggestion
We created this template to provide a clear scope and style for all recipes. This makes things easier and more
```

2022-11-10 20:41 UTC, AlexGaillard commented on cookbook/add-a-recipe.md
> +That said.... its nice to be able to break the rules sometimes.
```suggestion
That said.... it's nice to be able to break the rules sometimes.
```

2022-11-10 20:43 UTC, AlexGaillard commented
Overall I'd say it looks good. There is the consideration of adding an ``EXTRA READING`` or ```HELPFUL LINKS``` or ```REFERENCE LINKS``` section for more complex topics. Not sure if something like that was included and I just missed it.

2022-11-10 20:47 UTC, AlexGaillard commented on cookbook/add-a-recipe.md
> +  [How To Guide](#how-to-guide) below, they should have a general idea of what the recipe is, its general steps, and
```suggestion
  [How To Guide](#how-to-guide) below, they should have a general idea of what the recipe is, an overview of the steps involved, and
```

2022-11-10 20:48 UTC, AlexGaillard commented on cookbook/add-a-recipe.md
> +  [How To Guide](#how-to-guide) below, they should have a general idea of what the recipe is, its general steps, and
Just to avoid repetition of ```general```

2022-11-14 18:30 UTC, erondpowell commented
> Here you go @erondpowell, I made a few edits to the recipe for recipes.

Thx Alex! This will save me a lot of time in the proof-editing stage! 🙏

2022-11-15 09:40 UTC, br41nslug requested changes

2022-11-15 09:40 UTC, br41nslug commented on .vitepress/config.js
> +			{ text: 'Cookbook', link: 'http://localhost:5173/cookbook/add-a-recipe', activeMatch: '/cookbook/' },
Best to keep these URLs relative as they won't be changing domain i believe. That way the links will work too in any deployment.
```suggestion
			{ text: 'Docs', link: '/' },
			{ text: 'Cookbook', link: '/cookbook/add-a-recipe', activeMatch: '/cookbook/' },
```

2022-11-15 09:40 UTC, br41nslug commented on cookbook/add-a-recipe.md
> +  [How To Guide](#how-to-guide) below, they should have a general idea of what the recipe is, its general steps, and
`[How To Guide](#how-to-guide)` This link seems to go nowhere yet.

2022-11-15 09:40 UTC, br41nslug commented on cookbook/data-models/build-content-with-m2a.md
> +-->
Probably best to start looking into Youtube/Vimeo embeds for these video's instead as properly hosting video is quite a task.

2022-11-15 18:57 UTC, freekrai commented on cookbook/data-models/build-content-with-m2a.md
> +-->
I second this, or also consider mux for video embeds.

2022-11-15 18:58 UTC, freekrai approved these changes
Looks good, no comments outside of those posted by @br41nslug and @AlexGaillard though I would look at mux for video possibly, hosting video locally can get to be a pain.

2022-11-15 22:37 UTC, erondpowell commented on cookbook/data-models/build-content-with-m2a.md
> +-->
I spoke with brainslug about this and agree. 

@rijkvanzanten voted against Youtube February as we become more dependent over another platform.
However, I think accessible media contribution will be very very important for community engagement.

I'm currently imagining a custom component to handle this, which allows for media uploads from multiple sources.

```
<DocsMedia
   src1=“youtube.com/asf5h” 	
   src2=“www.vimeo/2q45”
   ...
/>
```
The component checks if the media link is broken, and uses the first valid source.
If all media links are broken, it has a v-show to hide the media entirely.

This approach would:
- let us failsafe our content + catalyze `Docs <-> Youtube` cross-traffic.
- let users use any hosting platform they prefer... *(or multiple!)*
- keep docs clean of broken media

2022-11-17 18:37 UTC, erondpowell commented
@AlexGaillard Big thanks again for the edits 🙏 

> EXTRA READING or HELPFUL LINKS or REFERENCE LINKS 

So we'll link heavily to the main docs (which I'm starting to call the "manual" atm).
Second, we'll have *tags* and a component to suggest related recipes.

Is that along the lines of what your were thinking? or something even more extensive?

2022-11-17 18:42 UTC, AlexGaillard commented
> Is that along the lines of what your were thinking? or something even more extensive?

Yeah I think so. Just really to keep the information flow moving so you can always go somewhere else to see/learn more.

2022-11-17 18:49 UTC, ConnorSimply approved these changes
Looks good to me! I think this format will help solve a lot of one off small use cases people are curious about setting up.

Big thing we should really push is creating an easy way to import/export these set-ups/cookbooks in the Admin App whether it is schemas, flows, permissions, etc.

2022-11-17 20:33 UTC, erondpowell commented
> Big thing we should really push is creating an easy way to import/export these set-ups/cookbooks in the Admin App whether it is schemas, flows, permissions, etc.

Yeah for sure. @licitdev pointed out, that could be quite the technical endeavor to get right. 
We both agreed it could easily be 6-18 months away, based on all constraints atm.
Opening an issue for this feature and tagging you (and other engineers) in another doc to log ideas/plans/details in depth.

2022-11-18 06:22 UTC, azrikahar reviewed
Looks great! 

Couple of additional thoughts/questions:

- Will `tags` or `skill_level` frontmatter have predefined values to adhere to? For tags, examples such as `M2A` vs `Many-to-Any` (or maybe both are required), or singular vs plural, might impact the filtering depending how the tags filtering will work. For `skill_level`, maybe predefined values would be more consistent.

- Is there any description for `author_override` frontmatter? 

- > Will this recipe template and contribution system be scalable? Can we see any scale-up issues?

    Slight concern is how would we determine "the recipe already exists", as it may require some "parsing" from maintainers to gauge much overlap it has with existing recipe(s). (maybe it's somewhat similar, but addresses another use case, but then should the existing recipe "absorb" this vs having another separate recipe etc. Might still ultimately be a case-by-case thing)

2022-11-18 06:22 UTC, azrikahar commented on cookbook/data-models/build-content-with-m2a.md
> +author_override:author: Eron Powell
```suggestion
author_override:
author: Eron Powell
```

(if I'm not mistaken!)

2022-11-18 14:50 UTC, AlexGaillard commented on cookbook/add-a-recipe.md
> +To help avoid these types of issues, we have all potential contributors follow these steps.
No, and I think it reads better.

2022-11-18 17:27 UTC, erondpowell commented
> Will `tags` or `skill_level` frontmatter have predefined values to adhere to? For tags, examples such as `M2A` vs `Many-to-Any` (or maybe both are required), or singular vs plural, might impact the filtering depending how the tags filtering will work. For `skill_level`, maybe predefined values would be more consistent.

It isn't decided yet, but I also lean to tags being pre-defined.

>  Is there any description for `author_override` frontmatter?

So currently, we hardcode `authors`. Eventually, Rijk said he wants to write a little script to get the author from `git`.
Author override is a part of that plan.

>   Slight concern is how would we determine "the recipe already exists", as it may require some "parsing" from maintainers to gauge much overlap it has with existing recipe(s). 

- Yeah good point. idk what's best for tagging, I have never done it. We'll absolutely have to read these recipes. 
- Also, in my mind, judgement of "viable recipes" will need to be a case-by-case basis, totally at our discretion. I think it unwise to treat this like medium.com, especially at the beginning with under 100 recipes in total 🐇  

What are your suggestions on these two ideas?

*On that note: if the cookbook 🧑‍🍳  blows up and we get like 1000 contributions within 6 months or something, we'll have to re-think whether we want to ride the potential SEO train  🚂 and let them all flood in in OR keep the content and DX clean and easy.*

2022-11-18 17:50 UTC, erondpowell commented on cookbook/flows/slugify-text-with-run-script.md
> +```
@freekrai also has a more robust slugify. I spent minutes deciding if I should steal his.
Decided not to to keep the base recipe as simple as possible, bc that's my personal style.
We can put stuff like that in the "final tips" section as well.
Then people can ask for help in Discord.

Another Idea: Eventually we'll have hundreds of recipes, and storing it all in markdown will become quite the chore. We'll probably want to use Directus at that point. I just imaged creating recipe *variants* using an O2M.

2022-11-21 19:56 UTC, erondpowell commented
@rijkvanzanten Let's do it 🤝 I'll let you curse through it one last time and squash+merge it.

2022-11-22 01:00 UTC, rijkvanzanten commented
Lets rework the navigational structure a bit. Right now, I don't think the navigation to the cookbook is obvious enough. It's the same issue we discussed one fateful call one fateful afternoon where notes where conveniently omitted from 😅 

![CleanShot 2022-11-21 at 19 52 07@2x](https://user-images.githubusercontent.com/9141017/203187970-d48b2388-0a58-43a6-9b32-e1c49cba57b7.png)

The top navigation is links to _external_ references, yet now the docs (current page) and cookbooks are included as well. Cookbooks are not an external website, but another sub-section of the docs. 

When clicking on cookbooks, the user is treated with a document on how to _Add a Recipe_, rather than an overview of recipes itself:

![CleanShot 2022-11-21 at 19 54 03@2x](https://user-
images.githubusercontent.com/9141017/203188137-3bb72945-32b2-449e-9af2-63a8be99663b.png)

I didn't realize there was more to navigate to at this point, as I'm not used to seeing different items under the subnav menu.

Speaking of the menu, we currently don't have a number of recipes yet that warrant a full override of the navigation menu:

<img width="302" alt="CleanShot 2022-11-21 at 19 54 29@2x" src="https://user-images.githubusercontent.com/9141017/203188218-fdebf1c2-8ac7-4d5b-a88e-8c1f2c812e63.png">

For this first release, I think we should make Cookbook a section of the regular navigation—probably between Configuration and API Reference—and just listing all available recipes underneath. Once we have too many recipes to comfortably fit there, we can move to a sub-nested structure (nest recipes by top level section (flows vs insights vs data model etc)), followed by a custom "home" template for the cookbook that has includes a navigational pattern that allows for easier searchability of the recipes.

As for the recipes themselves, lets stick to "real life use cases" instead of reference pieces on how to use a feature. For example, in "Build Content With M2A", the usage of a M2A isn't the _goal_, but the tool to achieve the job. Similarly, I'm wondering if we should call "Recursive Content Hierarchies" something more use case applicable, like "Nested Menu Structure" 🤔

2022-11-22 05:58 UTC, erondpowell commented
@rijkvanzanten

I didn't realize you definitely wanted cookbook off the nav-bar.
I'll put it into the main docs section for now and remove it from the navbar. 
and take notes **every time** we talk! 😇 🙈 

hmm, are they just "reference" pieces? 
I'd argue they are still base-case recipes. a step above references. 
And also argue the explanation given is *nice* and hard/inappropriate to fit in the main docs.
Of course I can modify these to be more *production ready* examples though.

If you want to chat it over, I can run my reasoning more quickly in a quick call.
Otherwise, send the orders and I will make them more *production ready*.

2022-11-22 16:59 UTC, johnwdaniels commented
This looks great - I think this will help with all the non-technical people and we can certainly add more guides as theres a ton out there - but this looks great. Can't wait to get this live!

2022-11-23 18:11 UTC, rijkvanzanten approved these changes

2022-11-23 18:11 UTC, merged