Improve js sdk doc
directus/docs pull request #244
Opened 2022-12-19 21:02 UTC by erondpowell

Closes: https://linear.app/directus/issue/DOCS-75

- [ ] ~~Refactor SDK endpoints into SnippetToggler.~~ (postponed)
- [ ] Rename it JS-SDK Config
- [ ] New Structure
```
Installation
Usage
Endpoints
TypeScript
Reference
Auth
Transport
Storage
```

- [ ] Smaller reorganizations on each section

2022-12-23 22:36 UTC, erondpowell commented
Tagged @br41nslug because we've been talking about this for a while and @freekrai because you're actively working on the sdk right now. If you get a chance, please take a look over this one and lmk what you think 🙏 
(cc @rijkvanzanten )

2022-12-23 22:38 UTC, freekrai approved these changes
Looks good

2022-12-23 23:11 UTC, erondpowell commented
@rijkvanzanten @phazonoverload I'll let one of you confirm a review before I hit "merge"

2022-12-23 23:21 UTC, phazonoverload commented
It's pretty late so will look next week. If all good can I merge it, or would you rather?

2022-12-24 01:34 UTC, erondpowell commented
> It's pretty late so will look next week. If all good can I merge it, or would you rather?

You can merge it, for sure

2022-12-24 17:50 UTC, rijkvanzanten requested changes

2022-12-24 17:50 UTC, rijkvanzanten commented on reference/sdk.md
> +	const publicData = await directus.items('some_public_collection').readByQuery({ meta: 'total_count' });
Lets not focus too heavily on `meta`. Ideally people rely on aggregation rather than the old `meta` query param.

2022-12-24 17:50 UTC, rijkvanzanten commented on reference/sdk.md
> +}
```suggestion
async function publicData() {
	// We don't need to authenticate if the public role has access.
	const publicData = await directus.items('some_public_collection').readByQuery({ sort: ['id'] });

	console.log(publicData.data);
}
```

2022-12-24 17:50 UTC, rijkvanzanten commented on reference/sdk.md
> +	const privateData = await directus.items('some_private_collection').readByQuery({ meta: 'total_count' });
Same meta thing

2022-12-24 17:50 UTC, rijkvanzanten commented on reference/sdk.md
> +export default {
Lets remove the `export default`s from these, that doesn't really fit in this context (you're not exporting any config, this is the config option you'd pass to Directus). Alternatively, if we don't want to start with just an object floating in space, we could make it:

```suggestion
const config = {
```

2022-12-24 17:50 UTC, rijkvanzanten commented on reference/sdk.md
> +		mode: typeof window === 'undefined'? 'json': 'cookie',
This is a tad confusing in context; lets go with browser user as the assumed default, and adding a comment for the Node.js environment difference:

```suggestion
		mode: 'cookie', // 'json' in Node.js
```

2022-12-24 17:50 UTC, rijkvanzanten commented on reference/sdk.md
> +		staticToken: '',
Is this an empty string or `null`?

2022-12-24 17:50 UTC, rijkvanzanten commented on reference/sdk.md
> +		onUploadProgress: (ProgressEvent) => void,
```suggestion
		onUploadProgress: (ProgressEvent) => {},
```

Maybe we can rely on destructuring to hint at what's available in the progress event, like:

```suggestion
		onUploadProgress: ({ percentage }) => void,
```

(`percentage` just an example, I don't know what's available in that event out of the top of my head)

2022-12-24 17:50 UTC, rijkvanzanten commented on reference/sdk.md
>  });
I _think_ we might wanna omit this with the eye on the bigger drop-axios sprint that's in the works, at which point this no longer exists.

2022-12-24 17:50 UTC, rijkvanzanten commented on reference/sdk.md
> +<br />
Are these necessary? If we need additional margin/padding, that should probably be solved in CSS rather than with empty lines without meaning

2022-12-24 17:50 UTC, rijkvanzanten commented on reference/sdk.md
> +Although it's not required, it is recommended to use Typescript to have an easy development experience. This allows more
```suggestion
Although it's not required, it is recommended to use TypeScript to have an easy development experience. This allows more
```

2022-12-24 17:50 UTC, rijkvanzanten commented on reference/sdk.md
> +const directus = new Directus<MyCollections>('http://url');
Lets use a more "real" demo URL, like

```suggestion
const directus = new Directus<MyCollections>('https://example.com');
```

2022-12-24 17:50 UTC, rijkvanzanten commented on reference/sdk.md
> +:::
Unrelated to this PR, but @freekrai lets see if the updates to SDK is a good time to make this a little less of a footgun. Async getters are not really common practice in JS anno 2022, so it's incredibly easy to make this mistake

2022-12-24 17:51 UTC, rijkvanzanten commented
Couple of tiny tweaks, but looks great overall 🙂

2022-12-24 17:54 UTC, erondpowell commented
> Couple of tiny tweaks, but looks great overall 🙂

Ok, I'll do these tweaks now and then merge it

2022-12-24 21:10 UTC, erondpowell commented
@rijkvanzanten These should be mostly patched up. I made new tickets for:
- CSS: DOCS-132
- Axios: DOCS-131

2022-12-27 15:20 UTC, br41nslug reviewed
A huge improvement 😄 But I did go a little wild on the naming suggestions

2022-12-27 15:20 UTC, br41nslug commented on reference/sdk.md
> +## `transport`
```suggestion
### Transport options
```

2022-12-27 15:20 UTC, br41nslug commented on reference/sdk.md
> +const directus = new Directus('https://example.directus.app', {
Shouldnt we promote the `// await directus.auth.login({ email, password })` method as the main way of authenticating with the use of static token as advanced sidenote

2023-01-03 19:22 UTC, merged

2023-01-03 21:04 UTC, freekrai commented on reference/sdk.md
> +:::
Yeah, this one has caused some pains before so can see what we can do there.