Write up files section
directus/docs pull request #25
Opened 2024-09-16 10:53 UTC by hola-soy-milk

2024-09-20 17:07 UTC, phazonoverload requested changes
Good start. I've noticed some phrases I wouldn't expect you to write so I think they've come through with a copy/paste. I'd rather you go a bit slower but take the time to handwrite these new docs, over copy/pasting by default. 

- Lowercase everything except proper nouns. The old docs had a lot of capitalization and I'd like to stop that going forward. 
- Access files page needs doing. It's just about the URL structure (no transforms but that can be linked to). Mention that if you're loading in a webpage with a cookie, it'll be used automatically. Otherwise, you can append an access_token query param to the URL with the right permissions.
- Thumbnails generally let's swap for 'transformed asset'.
- Name the createDirectus variable directus, not client. This is a general effort I've been making across the docs.

2024-09-20 17:07 UTC, phazonoverload commented on content/6.files/2.upload.md
> +Multiple files can be uploaded simultaneously via both the Data Studio and programmatically via the API. File uploads are not limited to just images, they can be any kind of file.
```suggestion
Multiple files can be uploaded simultaneously via both the Data Studio and via the API. File uploads are not limited to just images, they can be any kind of file.
```

API = programatically. No need to say it.

2024-09-20 17:07 UTC, phazonoverload commented on content/6.files/2.upload.md
> +Open the files module on the left. This will show your File Library. This acts as one big Folder to store all uploaded files. You can create sub-folders to keep these organized.
This is a lot of very short sentences which is slightly jarring to read -  I think they could be consolidated slightly.

2024-09-20 17:07 UTC, phazonoverload commented on content/6.files/2.upload.md
> +Create a folder called `Images` and click on +.
```suggestion
Create a folder called `Images` and click on :icon{name="material-symbols:add-circle-outline-rounded"}.
```

2024-09-20 17:07 UTC, phazonoverload commented on content/6.files/2.upload.md
> +Create a folder called `Images` and click on +.
You can use any icon id from https://icones.js.org - for example https://icones.js.org/collection/material-symbols?s=plus+&icon=material-symbols:add-circle-outline-rounded

2024-09-20 17:07 UTC, phazonoverload commented on content/6.files/2.upload.md
> +const client = createDirectus('https://directus.example.com').with(rest());
Can you rename this variable directus and the usage of it on l50?

2024-09-20 17:07 UTC, phazonoverload commented on content/6.files/3.manage.md
> +<!-- TODO: Bring over Data Studio icons -->
Ah yes - I've mentioned how to do this before.

2024-09-20 17:07 UTC, phazonoverload commented on content/6.files/3.manage.md
> +customized as needed in **Settings > Data Model**. However the pre-configured Fields cannot be changed or deleted.
```suggestion
The Files Collection comes pre-configured with the following Fields out of the box. New Fields can be created and
customized as needed in **Settings > Data Model**. However, the pre-configured Fields cannot be changed or deleted.
```

2024-09-20 17:07 UTC, phazonoverload commented on content/6.files/3.manage.md
> +- **Filename (Disk)**: LOCKED. This is the actual name of the file in storage.
Can you expand on 'LOCKED'

2024-09-20 17:07 UTC, phazonoverload commented on content/6.files/5.transform.md
> +Directus allows you to fetch thumbnails or processed images using a varied set of parameters. You can pass these as either query parameters to our REST API or via the Directus SDK. If a processed ima
Can we remove 'thumbnail' from our nomenclature - it's used nowhere else. I think 'transformed assets' would be better.

```suggestion
Directus allows you to transform assets using URL query parameters. You can pass these as either query parameters to our `assets` endpoint. If a processed image does not yet exist, it is dynamically generated, stored, and returned.
```

The SDK just generates the URL.

2024-09-20 17:07 UTC, phazonoverload commented on content/6.files/5.transform.md
> +```
No need for an example here.

2024-09-20 17:07 UTC, phazonoverload commented on content/6.files/5.transform.md
> +download will work on the _same_ domain, however it will have the file's "id" as the filename for cross-origin requests.
Move to accessing files page - this isn't about transforming.

2024-09-20 17:07 UTC, phazonoverload commented on content/6.files/5.transform.md
> +## Requesting a Thumbnail
Remove this heading as the whole page is about transforms. Promote all other headings one level up

2024-09-20 17:07 UTC, phazonoverload commented on content/6.files/5.transform.md
> +  shortcut for the below parameters
Custom first, which provides context for custom. Can you please explain where to do this?

Also notices 'is as easy' in the first para in this comment - take a sweep for these terms.

2024-09-20 17:07 UTC, phazonoverload commented on content/6.files/5.transform.md
> +When transforming an image with `width` and/or `height` parameters, the focal point is taken from the `focal_point_x` and `focal_point_y` coordinate values stored in the file object, cropping the ima
Otherwise, it is center... make sure to mention

2024-09-20 17:07 UTC, phazonoverload commented on content/6.files/5.transform.md
> +
Make sure quotes are straight - there's some curly ones in here

2024-09-20 17:07 UTC, phazonoverload commented on content/6.files/5.transform.md
> +Custom and advanced transformations can also be used in conjunction.
```suggestion
Custom and advanced transformations can also be used together.
```

No point for big word

2024-09-23 07:19 UTC, hola-soy-milk commented
Thank you so much for this feedback. I feel like I've got better clarity on how to prioritise writing up these sections.

I'll fix this and moving forward will prioritise a rewrite over moving over content.

2024-09-23 07:31 UTC, hola-soy-milk commented on content/6.files/3.manage.md
> +<!-- TODO: Bring over Data Studio icons -->
Could you please clarify, are you referring to your [comment on the usage of icons](https://github.com/directus/docs/pull/25#discussion_r1768920530)?

2024-09-23 07:34 UTC, hola-soy-milk commented on content/6.files/2.upload.md
> +const client = createDirectus('https://directus.example.com').with(rest());
Done and will do this moving forward!

2024-09-23 12:58 UTC, phazonoverload commented on content/6.files/3.manage.md
> +<!-- TODO: Bring over Data Studio icons -->
Yup

2024-09-23 15:06 UTC, hola-soy-milk commented
@phazonoverload I think I caught everything! Can you please take another look? Thanks again!

2024-09-23 15:15 UTC, phazonoverload requested changes
Couple of small suggestions and comments. Additionally:

- What's happened to the preset transformations section in transform.md? 
- Please write short descriptions for each page.

2024-09-23 15:15 UTC, phazonoverload commented on content/6.files/3.manage.md
> +:: -->
What's happening here? Assuming nothing?

2024-09-23 15:15 UTC, phazonoverload commented on content/6.files/4.access.md
> +::
This isn't quite enough. IF there is a cookie present, it will be used. Otherwise, you can use the `access_token` query parameter on the end of the URL. The token must belong to a user with the requisite access to read the file.

2024-09-23 15:15 UTC, phazonoverload commented on content/6.files/5.transform.md
> +Directus offers direct exposure to the sharp API, giving you access to more complex operations on images.
```suggestion
Directus allows full access to the [Sharp API](https://sharp.pixelplumbing.com/), giving you access to more complex image transformations.
```

2024-09-23 15:15 UTC, phazonoverload commented on content/6.files/5.transform.md
> +This is done using the transforms parameter, whose value consists of a two dimensional array. Each sub-array contains the name of the operation, followed by its arguments: `[["operation1", …arguments
```suggestion
This is done using the `transforms` parameter, whose value consists of a two dimensional array. Each sub-array contains the name of the operation, followed by its arguments: `[["operation1", …arguments], ["operation2", …otherArguments]]`.
```

2024-09-23 15:15 UTC, phazonoverload commented on content/6.files/5.transform.md
> +::callout{type="info" title="REST values"}
```suggestion
::callout{type="info" title="REST Values"}
```

Title casing for titles

2024-09-23 15:17 UTC, hola-soy-milk commented
@phazonoverload My apologies! I only pushed after writing 🤦‍♀️ but there's plenty to do here, I'll get it going!

2024-09-23 15:17 UTC, phazonoverload commented
> What's happened to the preset transformations section in transform.md?

Ah this was addressed but after I started the review. Could you expand and explain preset transformations in this document? The config is for more advanced environment variable configs.

2024-09-23 15:17 UTC, hola-soy-milk commented
You bet! I'll get this done

2024-09-23 15:18 UTC, hola-soy-milk commented on content/6.files/3.manage.md
> +:: -->
Nope, my bad, I overlooked this section

2024-09-23 15:41 UTC, hola-soy-milk commented
Thanks for your patience! Could you please take another look, @phazonoverload?

2024-09-23 15:43 UTC, phazonoverload approved these changes

2024-09-23 15:43 UTC, merged