Extensions Section
directus/docs pull request #27
Opened 2024-09-16 16:40 UTC by phazonoverload

Review question:

There are subtle differences to how each sandboxed API extension type are registered compared to their non-sandboxed counterparts. I've included this at the bottom of each type page. Is this the right place for it? Or should it be in the sandbox page? I'd prefer to not duplicate unless we can make it a reusable partial that makes sense in both contexts.

2024-09-26 13:23 UTC, hola-soy-milk requested changes
This is excellent work. 

I'm trying to really stick to the goal of the docs being a reference, so I think the structure you propose is best. It might however be good to make that note that there are subtle differences in the sandbox page.

Side note: Having API and App next to each other as categories of extensions is a bit hard to parse sometimes. I wonder if there's a way we can make this easier? 
I'm of course not suggesting to rename one of them, just thinking out loud.

2024-09-26 13:23 UTC, hola-soy-milk commented on content/10.extensions/0.overview.md
> +Extensions in Directus run within the same environment as the main application, allowing them to leverage existing access to underlying [services](/extensions/api-extensions/services) and [UI compone
The UI components link here is taking me to an empty page. Maybe it wasn't intended to be shown?

2024-09-26 13:23 UTC, hola-soy-milk commented on content/10.extensions/1.quickstart.md
> +When changing the `docker-compose.yml` file, you will need to restart Directus by pressing `Ctrl/Cmd+C` and then run `docker compose up` again.
Do we want to specify that this can also be done from the Docker app itself?

2024-09-26 13:23 UTC, hola-soy-milk commented on content/10.extensions/0.overview.md
> +[Hooks](/extensions/api-extensions/hooks) allow running code when events occur within Directus. Events are triggered on schedules, database events, schedules, or during the Directus application lifec
```suggestion
[Hooks](/extensions/api-extensions/hooks) allow running code when events occur within Directus. Events are triggered on schedules, database events, or during the Directus application lifecycle.
```

2024-09-26 13:23 UTC, hola-soy-milk commented on content/10.extensions/2.api-extensions/1.hooks.md
> +| `request.error`                | The request errors.                   | --                                          |
Is the "--" here a string?

2024-09-26 13:23 UTC, hola-soy-milk commented on content/_partials/extension-hook-footguns.md
> +Directus reads system collections to operate. Be careful when modifying the output of system collection `read` or `query` events. Also ensure not the diretly or indirectly emit the same event your ho
```suggestion
Directus reads system collections to operate. Be careful when modifying the output of system collection `read` or `query` events. Also ensure not to directly or indirectly emit the same event your hook is handling or you will create an infinite loop.
```

2024-09-26 13:23 UTC, hola-soy-milk commented on content/_partials/extension-hook-exceptions.md
> +The `collections` and `fields` system collections does not emit a `read` event. The `files` collection does not emit a `create` or `update` event on file upload. The `relations` collection does not e
```suggestion
The `collections` and `fields` system collections do not emit a `read` event. The `files` collection does not emit a `create` or `update` event on file upload. The `relations` collection does not emit a `delete` event.
```

2024-09-26 13:23 UTC, hola-soy-milk commented on content/10.extensions/2.api-extensions/1.hooks.md
> +The `schedule` event takes a cron string as the first argument and a callback function as the second argument. The cron string follows the following format:
Do we want to link to cron docs?

2024-09-26 13:23 UTC, hola-soy-milk commented on content/10.extensions/2.api-extensions/2.endpoints.md
> +| `emitter`   | [Event emitter](https://github.com/directus/directus/blob/main/api/src/emitter.ts) instance that can be used to emit custom events for other extensions |
```suggestion
| `emitter`   | [Event emitter](https://github.com/directus/directus/blob/main/api/src/emitter.ts) instance that can be used to emit custom events for other extensions. |
```

2024-09-26 13:23 UTC, hola-soy-milk commented on content/10.extensions/2.api-extensions/3.operations.md
> +			text: text,
```suggestion
			text,
```

Do we want to use property value shorthand here?

2024-09-26 13:23 UTC, hola-soy-milk commented on content/10.extensions/2.api-extensions/4.services.md
> +You cannot update the field name via Directus after creation.
Would it make sense to elaborate on when a field name can be edited? Or probably not, if I remember correctly.

2024-09-26 13:23 UTC, hola-soy-milk commented on content/10.extensions/2.api-extensions/4.services.md
> +You cannot update the field name via Directus after creation.
I think the wording here is throwing me off a little. What do you think about something like this?

```suggestion
You cannot update the field name via Directus after creating the field.
```

2024-09-26 13:23 UTC, hola-soy-milk commented on content/10.extensions/3.app-extensions/1.interfaces.md
> +```vue
Oddly enough, the syntax highlighting isn't working here. Wonder if JS would do the trick since there's no markup?

2024-09-26 13:23 UTC, hola-soy-milk commented on content/10.extensions/3.app-extensions/1.interfaces.md
> +| `options`             | array     | component
Does "component" need elaborating here? Or a full stop?

2024-09-26 13:23 UTC, hola-soy-milk commented on content/10.extensions/3.app-extensions/3.layouts.md
> +| `layoutQuery`   | object   | The user's layout query parameters. (e.g., sort, limit, etc) |
```suggestion
| `layoutQuery`   | object   | The user's layout query parameters. (e.g., sort, limit, etc). |
```

2024-09-26 13:23 UTC, hola-soy-milk commented on content/10.extensions/3.app-extensions/4.panels.md
> +| `options`     | array     | component                                                                                                                 | When an array, options contains user-configur
Should "component" here be capitalised or expanded upon?

2024-09-26 13:23 UTC, hola-soy-milk commented on content/10.extensions/3.app-extensions/7.ui-library.md
> +Explore the available components in our [Directus Components Playground](https://components.directus.io/). Here, you can
Should this be an external link?

2024-09-26 13:23 UTC, hola-soy-milk commented on content/10.extensions/5.marketplace/1.publishing.md
> +Directus hosts a registry mirroring npm, with enhanced search/filtering and security features like blocking/delisting. The Directus Extensions Registry is updated every few hours, and only the latest
Probably overkill to link NPM right

2024-09-26 13:23 UTC, hola-soy-milk commented on content/10.extensions/5.marketplace/1.publishing.md
> +Your npm package's `README.md` file is shown on the extension detail page. This can be updated by releasing a new version of your package to npm.
I'd love to have a link to an example if we don't already have a link to one I missed

2024-09-26 13:23 UTC, hola-soy-milk commented on content/10.extensions/0.overview.md
> +[Hooks](/extensions/api-extensions/hooks) allow running code when events occur within Directus. Events are triggered on schedules, database events, schedules, or during the Directus application lifec
Repetition of the word schedules

2024-09-26 13:25 UTC, phazonoverload commented on content/10.extensions/0.overview.md
> +Extensions in Directus run within the same environment as the main application, allowing them to leverage existing access to underlying [services](/extensions/api-extensions/services) and [UI compone
It's a broken link. Will fix it later. Should be UI Library

2024-09-26 13:26 UTC, phazonoverload commented on content/10.extensions/1.quickstart.md
> +When changing the `docker-compose.yml` file, you will need to restart Directus by pressing `Ctrl/Cmd+C` and then run `docker compose up` again.
Or if we want to be even more generic, we can just say they have to restart the docker container.

2024-09-26 13:26 UTC, phazonoverload commented on content/10.extensions/2.api-extensions/1.hooks.md
> +| `request.error`                | The request errors.                   | --                                          |
It needs removing. It means none.

2024-09-26 13:27 UTC, hola-soy-milk commented on content/10.extensions/1.quickstart.md
> +When changing the `docker-compose.yml` file, you will need to restart Directus by pressing `Ctrl/Cmd+C` and then run `docker compose up` again.
Yes I think I like that best

2024-09-26 13:27 UTC, phazonoverload commented on content/10.extensions/2.api-extensions/1.hooks.md
> +The `schedule` event takes a cron string as the first argument and a callback function as the second argument. The cron string follows the following format:
I don't think so. Showing the structure is gonna be enough for most.

2024-09-26 13:27 UTC, phazonoverload commented on content/10.extensions/2.api-extensions/3.operations.md
> +			text: text,
No we want to be explicit. Your suggestion is correct.

2024-09-26 13:28 UTC, hola-soy-milk commented on content/10.extensions/2.api-extensions/1.hooks.md
> +The `schedule` event takes a cron string as the first argument and a callback function as the second argument. The cron string follows the following format:
Makes sense!

2024-09-26 13:28 UTC, phazonoverload commented on content/10.extensions/2.api-extensions/4.services.md
> +You cannot update the field name via Directus after creation.
THE field but I'm happy with this suggestion

2024-09-26 13:29 UTC, phazonoverload commented on content/10.extensions/3.app-extensions/1.interfaces.md
> +| `options`             | array     | component
It's an array or a component. I've got in a post-beta issue to explain how to do options components.

2024-09-26 13:29 UTC, phazonoverload commented on content/10.extensions/3.app-extensions/4.panels.md
> +| `options`     | array     | component                                                                                                                 | When an array, options contains user-configur
Oh actually the formatting is just messed up. Should be array | component

2024-09-26 13:29 UTC, phazonoverload commented on content/10.extensions/3.app-extensions/7.ui-library.md
> +Explore the available components in our [Directus Components Playground](https://components.directus.io/). Here, you can
Whatcha mean?

2024-09-26 13:30 UTC, phazonoverload commented on content/10.extensions/5.marketplace/1.publishing.md
> +Directus hosts a registry mirroring npm, with enhanced search/filtering and security features like blocking/delisting. The Directus Extensions Registry is updated every few hours, and only the latest
Yeah

2024-09-26 13:30 UTC, phazonoverload commented on content/10.extensions/5.marketplace/1.publishing.md
> +Your npm package's `README.md` file is shown on the extension detail page. This can be updated by releasing a new version of your package to npm.
We don't but we can make one.

2024-09-26 15:54 UTC, hola-soy-milk commented on content/10.extensions/3.app-extensions/4.panels.md
> +| `options`     | array     | component                                                                                                                 | When an array, options contains user-configur
Oh good to know, thanks!

2024-09-26 15:57 UTC, hola-soy-milk commented on content/10.extensions/3.app-extensions/7.ui-library.md
> +Explore the available components in our [Directus Components Playground](https://components.directus.io/). Here, you can
I've noticed external links look like in the screenshot. 
![image](https://github.com/user-attachments/assets/9f7535ed-a3f1-48eb-a7d3-50540ebcaaf4)

Seeing as this is outside docs, was wondering if we should have it look like this. Dunno how to tbh. Maybe it's a domain thing.

2024-09-26 15:59 UTC, phazonoverload commented on content/10.extensions/3.app-extensions/1.interfaces.md
> +```vue
Or we just need to load the language into the syntax highlighter

2024-09-26 16:00 UTC, phazonoverload commented on content/10.extensions/3.app-extensions/7.ui-library.md
> +Explore the available components in our [Directus Components Playground](https://components.directus.io/). Here, you can
Oh I'll check the pattern as I built it heh. Might be "directus" in url.

2024-09-26 16:00 UTC, hola-soy-milk commented on content/10.extensions/3.app-extensions/1.interfaces.md
> +```vue
It's possible! But I could swear the code sample lower down was working..

2024-09-26 16:03 UTC, hola-soy-milk commented on content/10.extensions/3.app-extensions/1.interfaces.md
> +```vue
[Yes, can confirm this one lower down is working ](https://github.com/directus/docs/pull/27/files/d17515b5aa3aafc028918d8fcc9c2bc29cec3866#diff-7d737a488dca6dd213a0102e3879988e3225eab210bd09ba75886c8debba8a41R74)

![image](https://github.com/user-attachments/assets/c7f1cda0-2e5f-4fda-a524-450aa216f77f)

2024-09-27 10:41 UTC, phazonoverload commented on content/10.extensions/3.app-extensions/7.ui-library.md
> +Explore the available components in our [Directus Components Playground](https://components.directus.io/). Here, you can
This is fine, but fyi the rule is for links not to contain one of the following:

- directus.io
- directus.cloud
- localhost
- 127.0.0.1

In main.scss

2024-09-27 10:44 UTC, phazonoverload commented on content/10.extensions/5.marketplace/1.publishing.md
> +Your npm package's `README.md` file is shown on the extension detail page. This can be updated by releasing a new version of your package to npm.
Adding to backlog

2024-09-27 10:58 UTC, phazonoverload commented
@connorwinston do you mind taking a look at this? The UiAsideNav in ExtensionListing.global.vue is causing issues. I've confirmed that data._path exists for these pages.

2024-10-15 04:06 UTC, merged