Howto/headlesscms
directus/docs pull request #294
Opened 2023-02-13 18:39 UTC by bryantgillespie

## [How To Packet for Headless CMS](https://linear.app/directus/project/how-to-packet-headless-cms-33a3e2218a2f)

Includes:

- [MARK-110](https://linear.app/directus/issue/MARK-110/flows-triggering-static-site-builds)
- [MARK-113](https://linear.app/directus/issue/MARK-113/scheduling-content)
- [MARK-127](https://linear.app/directus/issue/MARK-127/create-re-usable-page-components)

2023-02-17 11:27 UTC, phazonoverload reviewed
I paused about 70 lines into the "Create re-usable page components" recipe. Couple of global points:

1. Title-case all headings. 
2. Use second-person "your", "you", instead of "ours", "we". 
3. This feels a lot bigger than a recipe - lots of background context an explanations. Reads like a solid blog post / article, but should it be more punchy for the recipe format? I'm asking @erondpowell what he thinks here (just look at `cookbook/data-models/create-reusable-page-components-using-m2a`). 

If we end up reworking this recipe to be much shorter and to-the-point, I want to not lose the longer-form content. I can already see several blog posts it can be turned into. 

Just wanna clear this one up and then I'll finish the review :)

2023-02-17 11:27 UTC, phazonoverload commented on cookbook/data-models/create-reusable-page-components-using-m2a.md
> +# Create re-usable page components
Title-case this

2023-02-17 11:27 UTC, phazonoverload commented on cookbook/data-models/create-reusable-page-components-using-m2a.md
> +A common use case when using Directus as a headless CMS’s is creating individual blocks that can be re-used on many
```suggestion
A common use case when using Directus as a headless CMS is creating individual blocks that can be re-used on many
```

2023-02-17 11:27 UTC, phazonoverload commented on cookbook/data-models/create-reusable-page-components-using-m2a.md
> +the quick outline:
```suggestion
This enables your content team create unique page layouts from re-usable components. To achieve this, you will:
```

2023-02-17 11:27 UTC, phazonoverload commented on cookbook/data-models/create-reusable-page-components-using-m2a.md
> +### Map out your data model
Title-case

2023-02-17 11:27 UTC, phazonoverload commented on cookbook/data-models/create-reusable-page-components-using-m2a.md
> +Directus first.
```suggestion
Before creating Collections inside of your Directus project, it’s helpful to think about your data model (schema).
```

2023-02-17 11:27 UTC, phazonoverload commented on cookbook/data-models/create-reusable-page-components-using-m2a.md
> +Directus first.
From the first half, it's implied that they'll be doing this outside of the platform

2023-02-17 11:27 UTC, phazonoverload commented on cookbook/data-models/create-reusable-page-components-using-m2a.md
> +Let’s break down our data model for each section.
```suggestion
Let’s break down the data model for each section.
```

2023-02-17 13:08 UTC, bryantgillespie commented
Thanks @phazonoverload 
> 1. Title-case all headings.
> 2. Use second-person "your", "you", instead of "ours", "we".

Good feedback. I will get the grammatical errors fixed asap.

> This feels a lot bigger than a recipe - lots of background context an explanations. Reads like a solid blog post / article, but should it be more punchy for the recipe format? I'm asking @erondpowell what he thinks here (just look at cookbook/data-models/create-reusable-page-components-using-m2a).

On this bit, I leave the final call up to you guys as it steps more into personal opinions. 

It's certainly longer than the existing recipes but there's also a lot of 'meat' to to achieving re-usable page components compared to other recipes. 

I can certainly rework it into a blog post and strip out of the all other non Directus bits if needed.

My take is that until we have a 'dedicated' home ready for this longer 'stuff', we should ship it as long as it checks the boxes below:

- [ ]  Is this technically correct?
- [ ] Is it easy to follow? Or does it confuse the reader?
- [ ] Does it help users achieve the stated result?
- [ ] If we release it, will it do any harm to the user or look bad on the product / company?

It can be helping users for now until we can come back to the "proper" format for this content.

2023-02-17 13:11 UTC, phazonoverload commented
Yeah, I think that's a sound point actually. It can always move about as new places exist for content. I'll continue the review with this in mind.

2023-02-17 20:55 UTC, erondpowell commented
@bryantgillespie

**First off, all the information in that "reusable components" page is really useful and awesome!**
But it needs to get re-written 🤠 

**There are 4 structural issues:**
- Kevin has a point, its not a recipe. It is **3 separate recipes and a tutorial**, all combined.
- The information for the "root recipe", create re-usable components, needs to be re-organized. A lot of info that should be in the "Explanation" and "Final Tips" sections is currently sitting in "The Recipe" section.
- Some bigger copy issues not related spelling/style/grammar. Strategic issues.
- There is still too much of "The Manual" living inside the recipe itself.

**I think we have two options:**

Option 1:
- Ship it as-is
- Meet and align on recipes **ASAP**
- Re-organize the content into 4 pieces of content
- Write them

I'm not against that! 
But we need to meet & align on recipes **before end of Feb**. 

Option 2:
- Hold back this one page
- Go over recipes together in detail
- Re-edit it
- Make tickets for the tutorial + other two recipes
    - Be sure to link the copy that belongs in other recipes and tutorials

I prefer option 2. But as long as it gets re-edited soon, *like before we make any more recipes*, I'm easy. 
I'll let you and @phazonoverload decide.

> On this bit, I leave the final call up to you guys as it steps more into personal opinions.

Btw, I don't agree following a content formula is an "opinionated" matter.
The 4 issues above are not about style, grammar, graphic design, or other presentation elements.
Recipes have a specific content formula, intended to deliver a specific end result, to a defined target audience.
It's about making sure that each recipe delivers on that.

2023-02-21 13:52 UTC, phazonoverload requested changes
Thanks so much for your patience while I got this review done. Another couple of suggestions added. 

Pending our convo today, I think the reusable page components recipe is, in fact, not a recipe, but can be lifted and dropped without many edits into a longer-form guide like my next/nuxt ones. 

One more top-level thing - make sure alt text contains everything needed for understanding in absence of the image being visible. Call out things which are of relevance and visible. For example 

![In the data model settings for the hero collection a section is highlighted. It reads "Collection naming translations" with a single item called "Hero".](https://user-images.githubusercontent.com/1461554/220363744-faf0943a-a9aa-44db-8d64-22e3a86a82f7.png)

`In the data model settings for the hero collection a section is highlighted. It reads "Collection naming translations" with a single item called "Hero".`

2023-02-21 13:52 UTC, phazonoverload commented on cookbook/data-models/create-reusable-page-components-using-m2a.md
> +---
Ok on reading this again, it's a super solid piece of work, but it isn't and shouldn't be a recipe as far as I'm concerned - this is a fully fledged guide on getting folks to create a basic project. Fortunately, I also have the guides written as part of this packet. So let's keep the content as-is, and just shift this from a recipe to a guide. We'll action this together.

2023-02-21 13:52 UTC, phazonoverload commented on cookbook/flows/scheduling-content-dynamic-sites.md
> +   b. For the Key, use something relevant like `date_published`.
Be authoritative here. Just tell them "Name the key `date_published`" They can extrapolate and change names of things if they want.

2023-02-21 13:52 UTC, phazonoverload commented on cookbook/flows/scheduling-content-dynamic-sites.md
> +Using the [Directus Javascript SDK](/reference/sdk) (preferred)
JavaScript *

2023-02-21 13:52 UTC, phazonoverload commented on cookbook/permissions/basic-workflows.md
> +# Building content approval workflows
title case

2023-02-21 17:27 UTC, bryantgillespie commented
> One more top-level thing - make sure alt text contains everything needed for understanding in absence of the image being visible. Call out things which are of relevance and visible.

@phazonoverload Thanks for this 🙏 . I had no idea the alt tags should be to this level of detail. And now also questioning every alt tag I've used on my own stuff for years. 😅

2023-02-22 13:46 UTC, phazonoverload requested changes
Great work! Only global change is to make sure H is capitalized: Headless CMS. The concepts page is super duper solid. I'm gonna pick up intro page, and adding my work to this PR today.

2023-02-22 13:46 UTC, phazonoverload commented on .vitepress/config.js
> +					text: 'Intro to Headless CMS',
Just make this `Introduction`

2023-02-22 13:46 UTC, phazonoverload commented on .vitepress/config.js
> +					link: '/use-cases/headless-cms/intro-to-headless-cms',
And, path wise, let's replace the last segment with `introduction`

2023-02-22 13:46 UTC, phazonoverload commented on .vitepress/config.js
> +					link: '/use-cases/headless-cms/headless-cms-concepts',
Same here: `Concepts`/`concepts`

2023-02-22 13:46 UTC, phazonoverload commented on .vitepress/config.js
> +					link: '/use-cases/headless-cms/create-reusable-page-components-using-m2a.md',
Remove .md

2023-02-22 13:46 UTC, phazonoverload commented on use-cases/headless-cms/create-reusable-page-components-using-m2a.md
> +**Sample Response**
Eron's suggestion included a dropdown here. Let's use it to reduce length of the page. https://github.com/directus/docs/pull/301/files#diff-2e2afe97be1ebc0b095c11394de97fddb177cdb93cc2def941ba9b671ed9b974R191-R257

2023-02-22 13:46 UTC, phazonoverload commented on use-cases/headless-cms/headless-cms-concepts.md
> +helpful definitions of terms you’ll likely see again.
```suggestion
If you’re new to using a Headless CMS, it can be hard to wrap your head around the terminology at first. Here’s some some
helpful definitions of terms you’ll likely see again.
```

2023-02-22 13:46 UTC, phazonoverload commented on use-cases/headless-cms/headless-cms-concepts.md
> +the API is what connects the content stored in the CMS to the front-end of the website or app.
```suggestion
APIs, or Application Programming Interfaces, are the glue between two systems. For example, in a Headless CMS,
the API is what connects the content stored in the CMS to the front-end of the website or app.
```

2023-02-22 13:46 UTC, phazonoverload commented on use-cases/headless-cms/headless-cms-concepts.md
> +
Add this - I think it's important to talk about fixed endpoints/params

> APIs provide a set of instructions on what data can be accessed and created - with a set of pre-defined options. It acts as a promise that, if you make a specific request, you get a known behavior and response - not dissimilar to a restaurant menu.

2023-02-22 13:46 UTC, phazonoverload commented on use-cases/headless-cms/headless-cms-concepts.md
> +### What is server side rendering (SSR)?
Swap this and the above - understanding dynamic/traditional web applications is kinda the pre-req to understanding static

2023-02-22 13:46 UTC, phazonoverload commented on use-cases/headless-cms/headless-cms-concepts.md
> +problem.
Remove this one imo - it's very specific to hosting providers and I don't think we touch on it in our guides?

2023-02-22 13:46 UTC, phazonoverload commented on use-cases/headless-cms/intro-to-headless-cms.md
> +description:
Directus' Data Studio and APIs are the perfect choice for your Headless CMS.

2023-02-22 13:46 UTC, phazonoverload commented on use-cases/headless-cms/intro-to-headless-cms.md
> +description:
Good start on this doc - I'm gonna pick it up from here.

2023-02-22 20:40 UTC, merged