New OpenAPI Spec
directus/docs pull request #30
Opened 2024-09-20 15:04 UTC by connorwinston

2024-10-06 22:20 UTC, bevis-hp commented
@phazonoverload I have completed converting the json endpoints from the generated oas to the paths folder.
There were a few fully issues I came across stopping me 100% the task due to primarily name changes and changes from the old docs or these could not be issues.
If you answer these questions I can polish it off.
- GraphQL snippet for 'Update a comment' in old docs is delete_comment? I assume that's a mistake, What is the correct name?
- Is there getAsset SDK&GQL snippet?
- 'List Auth Providers' (oauth) has no GraphQL example, is that correct?
- Is there 'Authenticated using an OAuth provider' (oauthProvider) SDK&GQL snippet? Is it the old 'Login Using SSO Providers' snippet?
- Is there 'updateExtensionBundle' SDK&GQL snippet?
- Is 'createFile' the new verison of 'importFile' or 'uploadFile'?
- Is there a 'createOperations' can only find 'createOperation' in json? Old docs reference both, have included the snippets for the 'createOperations' as the requestBody suggests it takes an array. 
- No Policies endpoints, cant find in the json?
- Is 'getMyPermissions' the new 'getUserPermissions'?
- 'schemaApply' doesn't have a generic request example, on a use example as is hard to make generic, what do you want to do here?
- Does 'updateLastUsedPageMe' need a SDK&GQL snipper, cant find any in old docs.
- Is 'Invite' under /user/invite/ the new 'registerUser' or the new 'inviteUser'? the request gives no hints to what SDK&GQL snippets needed.
- All of the utils rest enpoints have different names to the SDK and GQL, don't know if this is an issue.

2024-10-18 12:51 UTC, hola-soy-milk requested changes
Thanks so much! I just left the below comment that's blocking me from a straightforward review. Could you please take a look?

2024-10-18 12:51 UTC, hola-soy-milk commented on api-spec/index.yaml
>    "/permissions/{id}":
Just spoke about this with @phazonoverload, is it possible the other paths got removed or not added? Right now I'm only seeing `permissions`

2024-10-22 10:44 UTC, hola-soy-milk requested changes
Thank you for adding these! I'm afraid I can't get the docs to run now.

Please can you take a look at my comment

2024-10-22 10:44 UTC, hola-soy-milk commented on api-spec/index.yaml
> +  "/utils/cache/clear"
I'm afraid there's a `:` missing in this and the next few, giving me this error:

```
bundling ./api-spec/index.yaml...
Failed to parse API description at ./api-spec/index.yaml:

  - can not read an implicit mapping pair; a colon is missed in "/Users/carmenh/directus/docs/api-spec/index.yaml" (122:23)

 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
```

Adding them then generates a bunch of errors:

```
[27] api-spec/paths/webhooks/_id/updateWebhook.yaml:53:5 at #/responses/404
                                                                                                                                                                  
Can't resolve $ref: ENOENT: no such file or directory '/Users/carmenh/directus/docs/api-spec/paths/components/responses.yaml'
                                                                                                                                                                  
51 |     $ref: ../../components/responses.yaml#/UnauthorizedError
52 |   '404':
53 |     $ref: ../../components/responses.yaml#/NotFoundError
54 | tags:
55 | - Webhooks
                                                                                                                                                                  
Error was generated by the bundler rule.
```

2024-10-29 17:41 UTC, bevis-hp commented on api-spec/index.yaml
> +  "/utils/cache/clear"
Apologies. Very silly of me. Added them now.

2024-11-04 13:00 UTC, hola-soy-milk submitted a review, later dismissed
Thank you so much for this!

I've left a number of wording and formatting suggestions that I'm happy to handle myself.

I've also left a number of questions/requests. There's a number of endpoints and code snippets missing from the current documentation.

On a broader note:

- Is it possible to embed vue components into this?
- There is an inconsistent use of an example directus URL and a directus_url variable in code snippets. Can we make this consistent?
- In a few request body breakdowns, we show this `ANYOF` type. What is it? Can we add an explanation to it? See screenshot below.
Thanks in advance!

![image](https://github.com/user-attachments/assets/15cae27d-fee3-44ab-b33a-038fc68024f7)

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/assets/_id/getAsset.yaml
> +description: Image typed files can be dynamically resized and transformed to fit any
```suggestion
description: Image typed files can be retrieved, dynamically resized and transformed to fit any
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/assets/_id/getAsset.yaml
> +  description: A JSON array of image transformations
```suggestion
  description: A JSON array of image transformations.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/assets/_id/getAsset.yaml
> +  - label: GraphQL
Can we get a code sample here?

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/auth/login/login.yaml
> +summary: Retrieve a Temporary Access Token
```suggestion
summary: Login
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/auth/login/login.yaml
> +description: Retrieve a Temporary Access Token
```suggestion
description: Authenticate as a user.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/auth/login/login.yaml
> +            description: Email address of the user you're retrieving the access token
```suggestion
            description: Email address of the user you're logging in as.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/auth/login/login.yaml
> +  '200':
Is there a corresponding 400 here too?

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/auth/login/login.yaml
> +              or in a httpOnly cookie.
```suggestion
            description: Whether to retrieve the refresh token in the JSON response,
              or in a `httpOnly` cookie.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/auth/login/login.yaml
> +            default: json
```suggestion
            - `json`
            - `cookie`
            - `session`
            default: `json`
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/auth/login/login.yaml
> +  source: |
[Could it be we're missing an example with the provider parameter?](https://docs.directus.io/reference/authentication.html#login)

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/auth/logout/logout.yaml
> +description: Log Out
```suggestion
summary: Logout
description: Invalidate the refresh token thus destroying the user's session.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/auth/logout/logout.yaml
> +              or in a httpOnly cookie.
```suggestion
            - `json`
            - `cookie`
            - `session`
            description: Whether the refresh token is submitted in the JSON response,
              or in a `httpOnly` cookie.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/auth/logout/logout.yaml
> +    description: Request successful
Do we have an error state here too?

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/auth/logout/logout.yaml
> +    const client = createDirectus('directus_project_url').with(authentication()).with(rest());
Do we need the https://example here?

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/auth/oauth/oauth.yaml
> +summary: List OAuth Providers
```suggestion
summary: List Auth Providers
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/auth/oauth/oauth.yaml
> +description: List configured OAuth providers.
```suggestion
description: List all the configured auth providers.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/auth/oauth/oauth.yaml
> +  - label: GraphQL
This code snippet is empty

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/auth/oauth/_provider/oauthProvider.yaml
> +summary: Authenticated using an OAuth provider
```suggestion
summary: Log in Using an OAuth Provider
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/auth/oauth/_provider/oauthProvider.yaml
> +description: Start OAuth flow using the specified provider
```suggestion
description: Start OAuth flow using the specified provider.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/auth/oauth/_provider/oauthProvider.yaml
> +  description: Key of the activated OAuth provider.
It would be good to provide an example of a key here

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/auth/password/request/passwordRequest.yaml
> +description: Request a reset password email to be send.
```suggestion
description: Request a reset password email to be sent.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/auth/password/request/passwordRequest.yaml
> +        - email
[Missing the `reset_url` param](https://docs.directus.io/reference/authentication.html#request-password-reset)

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/auth/password/request/passwordRequest.yaml
> +  '401':
Missing 200 response

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/auth/password/request/passwordRequest.yaml
> +    const client = createDirectus('directus_project_url').with(rest());
For consistency, let's use the https variant

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/auth/password/request/passwordRequest.yaml
> +    const client = createDirectus('directus_project_url').with(rest());
The example URL that is

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/auth/password/reset/passwordReset.yaml
> +  '401':
Missing 200

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/auth/refresh/refresh.yaml
> +description: Refresh a Temporary Access Token.
```suggestion
description: Retrieve a new access token using a refresh token.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/auth/refresh/refresh.yaml
> +              response, or in a httpOnly cookie.
```suggestion
            - `json`
            - `cookie`
            - `session`
            default: json
            description: Whether to submit and retrieve the refresh token in the JSON
              response, or in a `httpOnly` cookie.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/schema/apply/schemaApply.yaml
> +    source: |
Code samples are empty

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/schema/diff/schemaDiff.yaml
> +  is only available to admin users.
```suggestion
description: |
  Compare the current instance's schema against the schema snapshot in JSON request body and retrieve the difference. This endpoint is only available to admin users.
  
  Alternatively, upload a JSON or YAML schema file. Relies on a `multipart/form-data` encoded request like regular file uploads. 
  
  This endpoint does not allow different Directus versions and database vendors by default. This is to avoid any
unintentional diffs from being generated. You can opt in to bypass these checks by passing the `force` query parameter.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/components/parameters.yaml
> +      - yaml
```suggestion
  description: Saves the API response to a file. Accepts one of `csv`, `json`, `xml`, `yaml`.
  in: query
  required: false
  schema:
    type: string
    enum:
      - `csv`
      - `json`
      - `xml`
      - `yaml`
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/server/info/serverInfo.yaml
> +description: Perform a system status check and return the options.
```suggestion
description: Provides detailed information about the project server, its schema, and its health.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/server/info/serverInfo.yaml
> +  '200':
[It would be good to have the contents of the response here](https://docs.directus.io/reference/system/server.html#response-1)

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/server/info/index.yaml
> +get:
[Seems we're missing the Health, SDL and OpenAPI specification endpoints](https://docs.directus.io/reference/system/server.html)

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/utils/cache/clear/clear-cache.yaml
> +summary: Clear Cache
```suggestion
summary: Clear the Internal Cache 
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/utils/cache/clear/clear-cache.yaml
> +description: Resets both the data and schema cache of Directus.
```suggestion
description: Resets the data cache of Directus. Optionally, can also clear system cache. This endpoint is only available to admin users.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/utils/cache/clear/clear-cache.yaml
> +x-codeSamples:
Do we need a curl example here too?

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/utils/export/_collection/export.yaml
> +            - json
```suggestion
            description: What file format to save the export to. One of `csv`, `xml`,
              `json`
            enum:
            - `csv`
            - `xml`
            - `json`
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/utils/export/_collection/export.yaml
> +description: Export a larger data set to a file in the File Library
```suggestion
description: Export a larger data set to a file in the file library.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/utils/hash/generate/hash-generate.yaml
> +summary: Hash a string
```suggestion
summary: Generate a Hash.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/utils/hash/verify/hash-verify.yaml
> +description: Generate a hash for a given string.
```suggestion
summary: Verify a Hash.
description: Verify a string with a hash.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/utils/sort/_collection/sort.yaml
> +summary: Sort Items
```suggestion
summary: Manually Sort Items in Collection 
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/utils/import/_collection/import.yaml
> +summary: Import Items
```suggestion
summary: Import Data from File 
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/utils/export/_collection/export.yaml
> +summary: Export Items
```suggestion
summary: Export Data to a File 
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/utils/export/_collection/export.yaml
> +            - json
```suggestion
            description: What file format to save the export to. One of `csv`, `xml`,
              `json`
            enum:
            - `csv`
            - `xml`
            - `json`
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/index.yaml
>      description: Group files by virtual folders.
```suggestion
    description: Folders can be used to organize files within the platform. Folders are virtual, and aren't mirrored within the storage adapter.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/folders/getFolders.yaml
> +description: List the folders.
```suggestion
description: List all folders that exist in Directus.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/folders/getFolders.yaml
> +responses:
[Is there a way we can describe the data structure?](https://docs.directus.io/reference/system/folders.html#response)

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/folders/createFolder.yaml
> +description: Create a new folder.
```suggestion
description: Create a new (virtual) folder.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/folders/deleteFolders.yaml
> +summary: Delete Multiple Folders
[This is missing parameters](https://docs.directus.io/reference/system/folders.html#delete-multiple-folders)

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/folders/_id/getFolder.yaml
> +description: Retrieve a single folder by unique identifier.
```suggestion
description: List an existing folder by primary key.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/folders/_id/updateFolder.yaml
> +description: Update an existing folder
```suggestion
description: Update an existing folder.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/folders/_id/deleteFolder.yaml
> +description: Delete an existing folder
```suggestion
description: Delete an existing folder. Any files in this folder will be moved to the root folder.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/relations/getRelations.yaml
> +description: List the relations.
```suggestion
description: List all relations that exist in Directus.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/relations/getRelations.yaml
> +summary: List Relations
[It would appear we're missing listing relations in a collection.](https://docs.directus.io/reference/system/relations.html#list-relations-in-collection)

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/index.yaml
> +    description: Files can be saved in any given location. Directus has a powerful assets endpoint that can be used to generate thumbnails for images on the fly.
```suggestion
    description: Every file managed by the platform is uploaded to the configured storage adapter, and its associated metadata is tracked within the `directus_files` system collection. Any requested file transformations are handled on the fly, and are only saved to storage.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/files/getFiles.yaml
> +description: List the files.
```suggestion
description: List all files that exist in Directus.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/files/createFile.yaml
> +description: Create a new file
```suggestion
summary: Upload a File 
description: Upload a new file.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/files/createFile.yaml
> +description: Create a new file
[If this is the equivalent of upload a file, there's the code snippets and params missing](https://docs.directus.io/reference/files.html#upload-a-file)

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/files/createFile.yaml
> +description: Create a new file
A number of endpoints is missing here too. See the documentation link above

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/files/deleteFiles.yaml
> +description: Delete multiple existing files.
```suggestion
description: Delete multiple existing files at once. This will also delete the files from disk.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/files/_id/getFile.yaml
> +description: Retrieve a single file by unique identifier.
```suggestion
summary: Retrieve a File
description: Retrieve a single file by primary key.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/files/_id/deleteFile.yaml
> +description: Delete an existing file.
```suggestion
description: Delete an existing file. This will also delete the file from disk.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/fields/_collection/_id/deleteField.yaml
> +description: Delete an existing field.
```suggestion
description: Delete an existing field. This action can't be undone.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/operations/getOperations.yaml
> +description: Get all operations.
```suggestion
description: List all operations that exist in Directus.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/operations/deleteOperations.yaml
> +summary: Delete Multiple Operations
[The body parameters are missing.](https://docs.directus.io/reference/system/operations.html#delete-multiple-operations)

Furthermore, a number of endpoints are missing, such as triggering an operation

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/operations/_id/getOperation.yaml
> +description: Retrieve a single operation by unique identifier.
```suggestion
description: Retrieve a single operation by primary key.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/operations/_id/updateOperation.yaml
> +description: Update an existing operation
```suggestion
description: Update an existing operation.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/versions/getContentVersions.yaml
> +description: Get all Content Versions.
```suggestion
description: List all Content Versions that exist in Directus.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/versions/createContentVersion.yaml
> +    const result = await client.request(createContentVersion(content_version_object));
```suggestion
    import { createDirectus, rest, createContentVersions } from '@directus/sdk';

    const client = createDirectus('directus_project_url').with(rest());

    const result = await client.request(createContentVersions(content_version_objects));
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/versions/createContentVersion.yaml
> +    	create_versions_item(data: create_directus_versions_input!): directus_versions
```suggestion
    	create_versions_items(data: create_directus_versions_input!): directus_versions
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/versions/createContentVersion.yaml
> +    	create_versions_item(data: create_directus_versions_input!): directus_versions
All samples including curl here are using the singular. Not sure where to fix this though

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/versions/deleteContentVersions.yaml
> +operationId: deleteContentVersions
[Body is missing](https://docs.directus.io/reference/system/versions.html#delete-multiple-content-versions)

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/versions/_id/promote/promoteContentVersion.yaml
> +          properties: {}
[This should be the primary key](https://docs.directus.io/reference/system/versions.html#response-10)

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/versions/_id/compare/compareContentVersion.yaml
> +responses:
[It would be good to have the same description as in the current docs](https://docs.directus.io/reference/system/versions.html#response-9)

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/versions/_id/promote/promoteContentVersion.yaml
> +  values are to be promoted (by default, all fields are selected).
```suggestion
description: Promote an existing Content Version to become the new main version of the item.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/versions/_id/save/saveContentVersion.yaml
> +        type: object
Is it possible to add more description of this body structure here?

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/revisions/getRevisions.yaml
> +description: List the revisions.
[Is it possible to inline info boxes here?](https://docs.directus.io/reference/system/revisions.html#list-revisions)

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/revisions/_id/getRevision.yaml
> +description: Retrieve a single revision by unique identifier.
```suggestion
description: List an existing revision by primary key.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/index.yaml
>      description: Users are what gives you access to the data.
```suggestion
    description: Directus Users are the individual accounts that let you authenticate into the API and App. Each user can belong to a Role.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/users/getUsers.yaml
> +description: List the users.
```suggestion
description: List all users that exist in Directus.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/users/deleteUsers.yaml
> +operationId: deleteUsers
[Request body is missing](https://docs.directus.io/reference/system/users.html#delete-multiple-users)

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/users/_id/getUser.yaml
> +description: Retrieve a single user by unique identifier.
```suggestion
description: List an existing user by primary key.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/users/invite/invite.yaml
> +summary: Invite User(s)
[Missing code snippets and body parameters](https://docs.directus.io/reference/system/users.html#invite-a-new-user)

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/users/invite/accept/acceptInvite.yaml
> +description: Accepts and enables an invited user using a JWT invitation token.
```suggestion
description: Accept your invite. The invite user endpoint sends the email a link to the Data Studio. This link includes a token, which is then used to activate the invited user.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/users/me/updateMe.yaml
> +responses:
Would it be good to include the request body here?

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/users/me/tfa/disable/meTfaDisable.yaml
> +summary: Disable 2FA
```suggestion
summary: Disable Two-Factor Authentication 
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/users/me/tfa/disable/meTfaDisable.yaml
> +description: Disables two-factor authentication for the currently authenticated user.
```suggestion
description: Disables two-factor authentication by removing the OTP secret from the user..
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/users/me/tfa/disable/meTfaDisable.yaml
> +description: Disables two-factor authentication for the currently authenticated user.
[Request body is missing](https://docs.directus.io/reference/system/users.html#request-body-10)

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/users/me/tfa/enable/meTfaEnable.yaml
> +description: Enables two-factor authentication for the currently authenticated user.
```suggestion
summary: Enable Two-Factor Authentication 
description: Adds a TFA secret to the user account.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/users/me/tfa/enable/meTfaEnable.yaml
> +description: Enables two-factor authentication for the currently authenticated user.
[Request body is missing](https://docs.directus.io/reference/system/users.html#request-body-9)

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/users/me/tfa/enable/meTfaEnable.yaml
> +description: Enables two-factor authentication for the currently authenticated user.
[Also, some endpoints are missing here](https://docs.directus.io/reference/system/users.html#generate-two-factor-authentication-secret)

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/users/me/track/page/updateLastUsedPageMe.yaml
> +description: Updates the last used page field of the currently authenticated user.
[Missing code snippets, but I couldn't find this in the original docs. Maybe we should remove it?](https://docs.directus.io/reference/system/users.html)

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/extensions/_bundle/_name/updateExtensionBundle.yaml
> +description: Update an existing extension.
Missing code snippets

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/webhooks/getWebhooks.yaml
> +    const result = await client.request(readWebhooks(query_object));
Missing params for the query object

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/webhooks/getWebhooks.yaml
> +responses:
Missing request params

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/settings/updateSetting.yaml
> +        type: object
Missing object structure

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/permissions/getPermissions.yaml
> +description: List all permissions.
```suggestion
description: List all permissions that exist in Directus.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/permissions/createPermission.yaml
> +description: Create a new permission.
```suggestion
summary: Create a Permission Rule
description: Create a new permission rule.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/permissions/createPermission.yaml
> +            - full
```suggestion
            - `none`
            - `create`
            - `update`
            - `full`
          create:
            type: string
            description: If the user can create items.
            enum:
            - `none`
            - `full`
          delete:
            type: string
            description: If the user can update items.
            enum:
            - `none`
            - `mine`
            - `role`
            - `full`
          explain:
            type: string
            description: If the user is required to leave a comment explaining what
              was changed.
            enum:
            - `none`
            - `create`
            - `update`
            - `always`
          read:
            type: string
            description: If the user can read items.
            enum:
            - `none`
            - `mine`
            - `role`
            - `full`
          role:
            type: integer
            description: Unique identifier of the role this permission applies to.
            example: 3
          read_field_blacklist:
            type: array
            description: Explicitly denies read access for specific fields.
            items:
              type: string
            example:
            - `featured_image`
          status:
            type: string
            description: What status this permission applies to.
          status_blacklist:
            type: array
            description: Explicitly denies specific statuses to be used.
            items:
              type: string
          update:
            type: string
            description: If the user can update items.
            enum:
            - `none`
            - `mine`
            - `role`
            - `full`
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/permissions/updatePermissions.yaml
> +                - full
```suggestion
                - `none`
                - `create`
                - `update`
                - `full`
              create:
                type: string
                description: If the user can create items.
                enum:
                - `none`
                - `full`
              delete:
                type: string
                description: If the user can update items.
                enum:
                - `none`
                - `mine`
                - `role`
                - `full`
              explain:
                type: string
                description: If the user is required to leave a comment explaining
                  what was changed.
                enum:
                - `none`
                - `create`
                - `update`
                - `always`
              read:
                type: string
                description: If the user can read items.
                enum:
                - `none`
                - `mine`
                - `role`
                - `full`
              role:
                type: integer
                description: Unique identifier of the role this permission applies
                  to.
                example: 3
              read_field_blacklist:
                type: array
                description: Explicitly denies read access for specific fields.
                items:
                  type: string
                example:
                - `featured_image`
              status:
                type: string
                description: What status this permission applies to.
              status_blacklist:
                type: array
                description: Explicitly denies specific statuses to be used.
                items:
                  type: string
              update:
                type: string
                description: If the user can update items.
                enum:
                - `none`
                - `mine`
                - `role`
                - `full`
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/permissions/updatePermissions.yaml
> +requestBody:
[Missing marking keys and data as required](https://docs.directus.io/reference/system/permissions.html#request-body-3)

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/permissions/deletePermissions.yaml
> +responses:
[Missing request body ](https://docs.directus.io/reference/system/permissions.html#request-body-4)

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/permissions/_id/updatePermission.yaml
> +            - full
```suggestion
            - `none`
            - `create`
            - `update`
          create:
            type: string
            description: If the user can create items.
            enum:
            - `none`
            - `full`
          delete:
            type: string
            description: If the user can update items.
            enum:
            - `none`
            - `mine`
            - `role`
            - `full`
          explain:
            type: string
            description: If the user is required to leave a comment explaining what
              was changed.
            enum:
            - `none`
            - `create`
            - `update`
            - `always`
          read:
            type: string
            description: If the user can read items.
            enum:
            - `none`
            - `mine`
            - `role`
            - `full`
          read_field_blacklist:
            type: object
            description: Explicitly denies read access for specific fields.
          role:
            type: object
            description: Unique identifier of the role this permission applies to.
          status:
            type: object
            description: What status this permission applies to.
          status_blacklist:
            type: object
            description: Explicitly denies specific statuses to be used.
          update:
            type: string
            description: If the user can update items.
            enum:
            - `none`
            - `mine`
            - `role`
            - `full`
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/permissions/me/getMyPermissions.yaml
> +summary: List My Permissions
[Missing code snippets](https://docs.directus.io/reference/system/permissions.html#get-current-user-permissions)

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/permissions/me/getMyPermissions.yaml
> +summary: List My Permissions
[This section is also missing endpoints](https://docs.directus.io/reference/system/permissions.html#create-multiple-permission-rules)

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/collections/_id/updateCollection.yaml
> +description: Update an existing collection.
```suggestion
description: Update the metadata for an existing collection.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/flows/getFlows.yaml
> +description: Get all flows.
```suggestion
description: List all flows that exist in Directus.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/flows/getFlows.yaml
> +description: Get all flows.
[Missing endpoints](https://docs.directus.io/reference/system/flows.html#flow-with-get-webhook-trigger)

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/flows/deleteFlows.yaml
> +responses:
[Missing body params](https://docs.directus.io/reference/system/flows.html#response-1)

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/flows/_id/updateFlow.yaml
> +description: Update an existing flow
```suggestion
description: Update an existing flow.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/presets/getPresets.yaml
> +description: List the presets.
```suggestion
description: List all presets that exist in Directus. The data returned in this endpoint will be filtered based on the user's permissions. For example, presets for a role other than the current user's role won't be returned.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/presets/deletePresets.yaml
> +responses:
[Missing body parameters](https://docs.directus.io/reference/system/presets.html#delete-multiple-presets)

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/roles/getRoles.yaml
> +description: List the roles.
```suggestion
description: List all roles that exist in Directus.
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/paths/roles/deleteRoles.yaml
> +responses:
[Missing request body params](https://docs.directus.io/reference/system/roles.html#delete-multiple-roles)

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/components/schemas/activity.yaml
> +      - login
```suggestion
      - `create`
      - `update`
      - `delete`
      - `login`
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/components/schemas/flows.yaml
> +      - inactive
```suggestion
      - `active`
      - `inactive`
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/components/schemas/permissions.yaml
> +      - delete
```suggestion
      - `create`
      - `read`
      - `update`
      - `delete`
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/components/schemas/settings.yaml
> +      - presets
```suggestion
      - `all`
      - `none`
      - `presets`
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/components/schemas/settings.yaml
> +            - outside
```suggestion
            - `cover`
            - `contain`
            - `inside`
            - `outside`
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/components/schemas/settings.yaml
> +            - avif
```suggestion
            - `jpeg`
            - `png`
            - `webp`
            - `tiff`
            - `avif`
```

2024-11-04 13:00 UTC, hola-soy-milk commented on api-spec/components/schemas/users.yaml
> +      - deleted
```suggestion
      - `active`
      - `invited`
      - `draft`
      - `suspended`
      - `deleted`
```

2024-11-05 15:33 UTC, hola-soy-milk commented
I've merged in my suggestions, leaving multiple points in my review to look at!

2024-11-15 14:57 UTC, hola-soy-milk commented
@be7DOTis please find the answers from engineering below:

> GraphQL snippet for 'Update a comment' in old docs is delete_comment? I assume that's a mistake, What is the correct name?

Dont think this is true, see below:
![image](https://github.com/user-attachments/assets/e0a5ffe4-0e94-4da7-9543-510ed3625e06)

> Is there getAsset SDK&GQL snippet?

Do you mean  a sdk&gql counterpart of the GET /assets/UUID endpoint? Those are here https://docs.directus.io/reference/files.html#custom

> 'List Auth Providers' (oauth) has no GraphQL example, is that correct?

This is correct

> Is there 'Authenticated using an OAuth provider' (oauthProvider) SDK&GQL snippet? Is it the old 'Login Using SSO Providers' snippet?

Are you looking for the "login" snippet as SSO provider is just an option with login

> Is there 'updateExtensionBundle' SDK&GQL snippet?

I am not aware of this being a function in the SDK or GQL or REST

> Is 'createFile' the new verison of 'importFile' or 'uploadFile'?

Same as above im not aware of "createFile" existing or replacing anything, currently you use either importFile or uploadFile

> Is there a 'createOperations' can only find 'createOperation' in json? Old docs reference both, have included the snippets for the 'createOperations' as the requestBody suggests it takes an array.

Yes this function exists hence it being in the current docs

> No Policies endpoints, cant find in the json?

they're all right here https://docs.directus.io/reference/system/policies.html

> Is 'getMyPermissions' the new 'getUserPermissions'?

No getMyPermissions is a variant of getUserPermissions that gets the current users permissions

> 'schemaApply' doesn't have a generic request example, on a use example as is hard to make generic, what do you want to do here?

The generic example for this endpoint is, you send this endpoint the output from schemaDiff thats it.

> Does 'updateLastUsedPageMe' need a SDK&GQL snipper, cant find any in old docs.

No clue, this is not an endpoint im aware of

> Is 'Invite' under /user/invite/ the new 'registerUser' or the new 'inviteUser'? the request gives no hints to what SDK&GQL snippets needed.

No registering and inviting users are 2 separate features with inviting pre-dating registering. Both inviting and registering have snippets available in the current docs https://docs.directus.io/reference/system/users.html#register-a-new-user

> All of the utils rest enpoints have different names to the SDK and GQL, don't know if this is an issue.

How do you mean? REST endpoints arent explicitly named

2024-11-19 19:39 UTC, bevis-hp commented on api-spec/paths/assets/_id/getAsset.yaml
> +  - label: GraphQL
Done

2024-11-19 19:44 UTC, bevis-hp commented on api-spec/paths/auth/login/login.yaml
> +  '200':
Not in the OAS but I can infer it from other endpoints but without testing or searching the codebase I cant confirm what they are.

2024-11-19 19:46 UTC, bevis-hp commented on api-spec/paths/auth/login/login.yaml
> +  source: |
I believe that is different endpoint linked to the registering endpoints. They not found in the OAS but I can add but where should it go. Under /auth?

2024-11-19 19:47 UTC, bevis-hp commented on api-spec/paths/auth/logout/logout.yaml
> +    description: Request successful
Again its not in the OAS but I can infer it from other endpoints but without testing or searching the codebase I cant confirm what they are

2024-11-19 19:49 UTC, bevis-hp commented on api-spec/paths/auth/oauth/oauth.yaml
> +  - label: GraphQL
Fixed, there is no GraphQL for this

2024-11-19 19:50 UTC, bevis-hp commented on api-spec/paths/auth/oauth/_provider/oauthProvider.yaml
> +  description: Key of the activated OAuth provider.
Maybe, I dont know what that looks like.

2024-11-19 19:56 UTC, bevis-hp commented on api-spec/paths/auth/password/request/passwordRequest.yaml
> +        - email
Indeed it is. Maybe because its optional and requires configuring an enviroment variable. I dont know what that looks like and maybe need 2 different snippets?

2024-11-19 19:58 UTC, bevis-hp commented on api-spec/paths/auth/password/request/passwordRequest.yaml
> +    const client = createDirectus('directus_project_url').with(rest());
Ah I made it consistant the other way to be directus_project_url. Is that an issue? Can change all to be https://directus.example.com instead but I feel that is better for example usage instead.

2024-11-19 19:59 UTC, bevis-hp commented on api-spec/paths/schema/apply/schemaApply.yaml
> +    source: |
Yes im a little stuck here as per the enginner "The generic example for this endpoint is, you send this endpoint the output from schemaDiff thats it." What should be written here in this case?

2024-11-19 20:04 UTC, bevis-hp commented on api-spec/paths/server/info/serverInfo.yaml
> +  '200':
I agree. Done

2024-11-19 20:09 UTC, bevis-hp commented on api-spec/paths/utils/cache/clear/clear-cache.yaml
> +x-codeSamples:
I dont think so. Kevin told me the REST snippets are generated automatically?

2024-11-19 20:12 UTC, bevis-hp commented on api-spec/paths/utils/export/_collection/export.yaml
> +            - json
Are we supposed to be using backticks in cases like this. Thought YAML doesnt like backticks?

2024-11-19 20:16 UTC, bevis-hp commented on api-spec/paths/folders/getFolders.yaml
> +responses:
I think that would be found under the Folder schema?

2024-11-19 20:22 UTC, bevis-hp commented on api-spec/paths/folders/deleteFolders.yaml
> +summary: Delete Multiple Folders
Indeed. A lot delete endpoints seems to be missing parameters and request body both in the OAS and Docs. I can maybe infer from the snippet.

2024-11-19 20:27 UTC, bevis-hp commented on api-spec/paths/files/createFile.yaml
> +description: Create a new file
Indeed. Do not know what to do here. Do I just dismiss the OAS and make the endpoints found in Docs?

2024-11-19 20:50 UTC, bevis-hp commented on api-spec/paths/users/me/track/page/updateLastUsedPageMe.yaml
> +description: Updates the last used page field of the currently authenticated user.
Indeed. Probably should not known by enginner either.

2024-11-19 20:50 UTC, bevis-hp commented on api-spec/paths/extensions/_bundle/_name/updateExtensionBundle.yaml
> +description: Update an existing extension.
Done

2024-12-16 12:25 UTC, merged