Write up Realtime section
directus/docs pull request #31
Opened 2024-09-21 11:02 UTC by hola-soy-milk

~~Gonna make this a draft in order to adapt based on the feedback from #25~~

Ready for review!

2024-09-23 17:25 UTC, phazonoverload requested changes
GOOD. 

An idea - for Authentication can we remove the H2s, promote the H3s and under each one (Public, Handshake, Strict) include both WebSockets and GraphQL Subscriptions as the H3s? What do you think? 

Generally, can you go through all headings and check they're all title case please. 

Spotted a couple of missing periods at end of sentences. Can you sweep for others.

2024-09-23 17:25 UTC, phazonoverload commented on content/8.realtime/2.authentication.md
> +Authentication is an important part of establishing your persistent connection with a Directus project.
This feels a little bit unnecessary. I do agree that there needs to be some preamble, but I don't think this is it. Sorry to not be more helpful.

2024-09-23 17:25 UTC, phazonoverload commented on content/8.realtime/2.authentication.md
> +| **strict**    | Authentication is required as a URL parameter on the initial connection.                                        |
Backtick these

2024-09-23 17:25 UTC, phazonoverload commented on content/8.realtime/2.authentication.md
> +There are three authentication modes in Directus.
Maybe mention handshake is default

2024-09-23 17:25 UTC, phazonoverload commented on content/8.realtime/2.authentication.md
> +setting the `WEBSOCKETS_REST_AUTH`, `WEBSOCKETS_GRAPHQL_AUTH` and `WEBSOCKETS_LOGS_AUTH` environment variables.
```suggestion
You can only use one authentication mode per project.

If self-hosting your project, you can change the mode used by setting the `WEBSOCKETS_REST_AUTH`, `WEBSOCKETS_GRAPHQL_AUTH` and `WEBSOCKETS_LOGS_AUTH` environment variables.
```

Not quite right as you can use diff auth mode per env var. I'll leave that with you to remedy.

2024-09-23 17:25 UTC, phazonoverload commented on content/8.realtime/2.authentication.md
> +WebSockets and GraphQL Subscriptions use the same globally-set configuration for the rate limiter and messenger.
I'd remove this personally. It's covered in config and we don't call this out in other areas.

2024-09-23 17:25 UTC, phazonoverload commented on content/8.realtime/3.subscriptions.md
> +When a change happens to an item in a collection with an active subscription, it will emit a message
```suggestion
When a change happens to an item in a collection with an active subscription, it will emit a message.
```

2024-09-23 17:25 UTC, phazonoverload commented on content/8.realtime/3.subscriptions.md
> +When a change happens to an item in a collection with an active subscription, it will emit a post
```suggestion
When a change happens to an item in a collection with an active subscription, it will emit a post.
```

2024-09-24 12:53 UTC, hola-soy-milk commented on content/8.realtime/2.authentication.md
> +Authentication is an important part of establishing your persistent connection with a Directus project.
Gonna remove it. Maybe conciseness can work in our favour. I wasn't happy with this either, so I'm glad to have it confirmed!

2024-09-24 13:40 UTC, hola-soy-milk commented
Think we're ready for a second pass, please! Thank you @phazonoverload I liked your ideas a lot and didn't find anymore missing full stops.

2024-09-24 14:10 UTC, phazonoverload requested changes
Fab. Just a couple of tiny tiny comments and then LGTM

2024-09-24 14:10 UTC, phazonoverload commented on content/8.realtime/2.authentication.md
> +There are three authentication modes in Directus:
```suggestion
There are three authentication modes in Directus Realtime.
```

2024-09-24 14:10 UTC, phazonoverload commented on content/8.realtime/2.authentication.md
> +
```suggestion
| Mode            | Description                                                                                                                 |
| --------------- | --------------------------------------------------------------------------------------------------------------------------- |
| **`public`**    | No authentication is required.                                                                                              |
| **`handshake`** | No authentication required to connect. First message must be an authentication request sent before the timeout. |
| **`strict`**    | Authentication is required as a URL parameter on the initial connection.                                                    |

`handshake` is the default authentication mode.
```

2024-09-24 14:10 UTC, phazonoverload commented on content/8.realtime/2.authentication.md
> +`access_token` and reconnect.
Lets move this down to the bottom - it's almost a footnote.

2024-09-24 14:12 UTC, hola-soy-milk commented on content/8.realtime/2.authentication.md
> +
This is much better, thank you

2024-09-24 14:20 UTC, hola-soy-milk commented
Should now be sorted, thank you @phazonoverload !

2024-09-24 15:35 UTC, phazonoverload approved these changes

2024-09-24 15:35 UTC, merged