Write Automate section
directus/docs pull request #35
Opened 2024-09-27 16:41 UTC by hola-soy-milk

2024-10-08 14:21 UTC, phazonoverload requested changes
Good - some general notes. Nothing big. For the triggers/operations I would suggest alphabetizing them.

2024-10-08 14:21 UTC, phazonoverload commented on content/7.automate/1.quickstart.md
> +Navigate to the [Flows](/automate/flows) section in the Settings module. Click on :icon{name="material-symbols:add-circle"} in the page header, which will cause a drawer to open. Fill in the name "Po
I wouldn't link to other sections from here - we want them to get through this guide swiftly and then link in a next steps section

2024-10-08 14:21 UTC, phazonoverload commented on content/7.automate/1.quickstart.md
> +Navigate to the [Flows](/automate/flows) section in the Settings module. Click on :icon{name="material-symbols:add-circle"} in the page header, which will cause a drawer to open. Fill in the name "Po
I also think this is a bit verbose overall.

```suggestion
Navigate to the Flows section in the Settings module. Click on :icon{name="material-symbols:add-circle"} in the page header and name the new flow "Post Created".
```

2024-10-08 14:21 UTC, phazonoverload commented on content/7.automate/1.quickstart.md
> +and select "Filter (Blocking)".
This should not be a filter - it should be an action as it doesn't need to block the db transaction. I would also explain what this option does.

2024-10-08 14:21 UTC, phazonoverload commented on content/7.automate/1.quickstart.md
> +Select `items.create` as the scope, and then check the "Posts" collection. Finally, select "Data of Last Operation".
I would also explain both the scope and the returned data option.

2024-10-08 14:21 UTC, phazonoverload commented on content/7.automate/1.quickstart.md
> +Now, when you create a post, the email address you entered will be notified.
Add a next steps section - this is the case in every quick start.

2024-10-08 14:21 UTC, phazonoverload commented on content/7.automate/1.quickstart.md
> +Here, you can create an [operation](/automate/operations). Give it the name "Notify Post Created" and the key "notify_post_created" will be written alongside.
Unlink

2024-10-08 14:21 UTC, phazonoverload commented on content/7.automate/1.quickstart.md
> +Select the "Send Email" operation type. Fill in the "To", "Subject" and "Body" fields accordingly.
I would also pick a different operation personally. The most basic quickstart docker compose does not set up a mail service so this will just fail. Maybe a notification as that's all in-app?

2024-10-08 14:21 UTC, phazonoverload commented on content/7.automate/2.flows.md
> +description: Learn to use Flows in Directus Automate.
```suggestion
description: Flows enable custom, event-driven data processing and task automation within Directus.
```

2024-10-08 14:21 UTC, phazonoverload commented on content/7.automate/2.flows.md
> +Flows enable custom, event-driven data processing and task automation within Directus. Each flow is composed of one trigger, a series of operations and a data chain.
```suggestion
Flows enable custom, event-driven data processing and task automation within Directus. Each flow is composed of one trigger, a series of operations, and a data chain that is passed between each step.
```

2024-10-08 14:21 UTC, phazonoverload commented on content/7.automate/2.flows.md
> +::
I think this is a lot for just marking one as required - instead maybe add `(required)` above?

2024-10-08 14:21 UTC, phazonoverload commented on content/7.automate/2.flows.md
> +- **Activity and Logs Tracking** — Lets you **Track Activity and Logs**, **Activity**, or **Neither**.
Explain this option more

2024-10-08 14:21 UTC, phazonoverload commented on content/7.automate/2.flows.md
> +triggers as well as each operation in the flow. To access a flow's logs, follow these steps.
```suggestion
Accessible from the sidebar, logs store information for each flow execution. Each log will display information from
triggers as well as each operation in the flow.
```

2024-10-08 14:21 UTC, phazonoverload commented on content/7.automate/2.flows.md
> +- **Payload** — Displays the data appended under `$trigger`.
Explain what the payload is

2024-10-08 14:21 UTC, phazonoverload commented on content/7.automate/2.flows.md
> +- **Accountability** — Displays data appended under `$accountability`.
Explain what accountability is

2024-10-08 14:21 UTC, phazonoverload commented on content/7.automate/2.flows.md
> +
Is there not also another outcome/result one too?

2024-10-08 14:21 UTC, phazonoverload commented on content/7.automate/2.flows.md
> +need to periodically delete this data.
Can you make this a bit more succinct? It's quite chatty like the previous docs

2024-10-08 14:21 UTC, phazonoverload commented on content/7.automate/2.flows.md
> +operation in the flow.
Same here - too verbose and chatty for a manual

2024-10-08 14:21 UTC, phazonoverload commented on content/7.automate/3.data-chain.md
> +description: Learn how to work with a Flow's data chain in Directus Automate.
Can you work on this to explain, in one line, what the data chain is?

2024-10-08 14:21 UTC, phazonoverload commented on content/7.automate/3.data-chain.md
> +this object after it runs. This means you can dynamically access data from a previous operation in the current operation
```suggestion
this object after it runs. This means you can dynamically access data from a previous operation or trigger in the current operation
```

2024-10-08 14:21 UTC, phazonoverload commented on content/7.automate/3.data-chain.md
> +```
Could you change this from inline comments to empty objects and then an explainer underneath?

2024-10-08 14:21 UTC, phazonoverload commented on content/7.automate/3.data-chain.md
> +You can mix your own hard-coded JSON alongside variables. You can also use dot-notation and array indexing to retrieve sub-nested values:
```suggestion
You can mix your own hardcoded JSON alongside variables. You can also use dot notation and array indexing to retrieve nested values:
```

2024-10-08 14:21 UTC, phazonoverload commented on content/7.automate/4.triggers.md
> +description: Learn how to work with Triggers in Directus Automate.
Again, one liner for what triggers are

2024-10-08 14:21 UTC, phazonoverload commented on content/7.automate/4.triggers.md
> +button within the Data Studio.
```suggestion
A trigger defines the event that starts a [Flow](/automate/flows). This could be from an internal or external activity, such as
changes to data, logins, errors, incoming webhooks, schedules, operations from other Flows, or even the click of a
button within the Data Studio.
```

2024-10-08 14:21 UTC, phazonoverload commented on content/7.automate/4.triggers.md
> +the Flow runs three separate times. On each run, just one item will be in the payload.
```suggestion
If you create items in a single request, the flow will trigger once for each item. If you create three items,
the flow runs three separate times. On each run, just one item will be in the payload.
```

Examples of capitalization and verbosity - can you sweep for both of these please. It's only Flows when we talk about it as a product. But as an instance, a flow.

2024-10-08 14:21 UTC, phazonoverload commented on content/7.automate/4.triggers.md
> +the database.
Mention no ID as it's not been created yet

2024-10-08 14:21 UTC, phazonoverload commented on content/7.automate/4.triggers.md
> +automatically. These item IDs are passed in to `$trigger`.
```suggestion
The manual trigger must take in item ID(s) before you can click it. On the collection page, the button will be
grayed out until you select some number of items. From the item page, the current item's ID is passed in
automatically. These item IDs are passed in to `$trigger` as an array.
```

2024-10-08 14:21 UTC, phazonoverload commented on content/7.automate/5.operations.md
> +description: Learn to work with operations in Directus Automate.
Same comment - explain what they are in one line

2024-10-08 14:21 UTC, phazonoverload commented on content/7.automate/5.operations.md
> +[operation extension](/extensions//api-extensions/operations) instead.
```suggestion
[operation extension](/extensions/api-extensions/operations) instead.
```

2024-10-08 14:21 UTC, phazonoverload commented on content/7.automate/5.operations.md
> +This operation sends off emails.
Written weirdly imo. I would also state that email must be configured correctly if self hosting and link to the configuration page

2024-10-08 14:21 UTC, phazonoverload commented on content/7.automate/5.operations.md
> +  it.
I think 'hit enter' is enough

2024-10-08 14:21 UTC, phazonoverload commented on content/7.automate/5.operations.md
> +- **Users** — Define a user by their UUID. Hit `↵` `Enter` (PC) or `return` (Mac) to save it. Click on a pill to remove
Same for any more examples like this - "hit enter" is enough

2024-10-09 14:09 UTC, hola-soy-milk commented on content/7.automate/2.flows.md
> +- **Payload** — Displays the data appended under `$trigger`.
data being passed into the flow

2024-10-09 14:09 UTC, phazonoverload commented on content/7.automate/2.flows.md
> +- **Accountability** — Displays data appended under `$accountability`, which is a breakdown of the permissions and request information of the user that triggered that event..
```suggestion
- **Accountability** — Displays data appended under `$accountability`, which is a breakdown of the permissions and request information of the user that triggered that event.
```

2024-10-09 15:06 UTC, hola-soy-milk commented
Thank you so much for this feedback! Could you please take another look?

2024-10-09 15:54 UTC, phazonoverload commented on content/7.automate/1.quickstart.md
> +Read more about [triggers](/automate/triggers), [the data chain](/automate/data-chain), and then refer to the Flows API reference to manage user accounts.
```suggestion
Read more about different [triggers](/automate/triggers) available in flows and how data is passed through a flow with [the data chain](/automate/data-chain), and .
```

2024-10-09 15:55 UTC, phazonoverload commented on content/7.automate/2.flows.md
> +Note that `$accountability` is not nested under the `$trigger` key. However, it is listed under the Trigger in the Log
```suggestion
Note that `$accountability` is not nested under the `$trigger` key. However, it is listed under the trigger in the log
```

2024-10-09 15:56 UTC, phazonoverload approved these changes
LGTM

2024-10-09 15:56 UTC, merged