Write up Content section
directus/docs pull request #37
Opened 2024-10-10 12:53 UTC by hola-soy-milk

2024-10-16 09:54 UTC, phazonoverload requested changes
Good. Mostly small changes. Global comments: 

- Watch random capitalization. 
- TODO all comments with images that need creating so we don't lose them.

2024-10-16 09:54 UTC, phazonoverload commented on content/3.content/1.explore.md
> +`AND` groups give the option to filter for items that meet all of several criteria. On the other hand, `OR` groups filter for items that meet any one of several criteria.
I'd mention here that to be part of the group, it needs to be indented under the AND or OR.

2024-10-16 09:54 UTC, phazonoverload commented on content/3.content/1.explore.md
> +The following dynamic variables are built into Directus to add extra functionality to filters: `$CURRENT_USER`, `$CURRENT_ROLE`, `$CURRENT_ROLES`, `$CURRENT_POLICIES`, `$NOW` and `$NOW(<adjustment>)`
Go through and explain what each one is. I'd also be clear that CURRENT_ROLES and CURRENT_POLICIES are arrays

2024-10-16 09:54 UTC, phazonoverload commented on content/3.content/1.explore.md
> +You can [select a layout](/content/layouts) for displaying your collection. Note that restrictions will apply depending on your collection's [data model](/data-modeling/collections).
I'd briefly explain more what these are. I know that it's a whole page, but I don't think this helps people understand them

2024-10-16 09:54 UTC, phazonoverload commented on content/3.content/1.explore.md
> +By selecting more than one item in the explorer will allow you to click on :icon{name="material-symbols:filter-list} and edit several items' fields at once.
Mention that this is to the same value.

2024-10-16 09:54 UTC, phazonoverload commented on content/3.content/1.explore.md
> +Bookmarks are custom layouts that can be displayed for different views of your collections.
Not quite. They specifically include more than layouts - also config, visible fields, sorting, filtering, search.

2024-10-16 09:54 UTC, phazonoverload commented on content/3.content/2.editor.md
> +The item editor is a tailored form for managing items and their field values.
Maybe mention it's specifically a SINGLE item?

2024-10-16 09:54 UTC, phazonoverload commented on content/3.content/2.editor.md
> +To create an Item, navigate to the content module and select the desired collection. Click :icon{name="material-symbols:add-circle-outline-rounded"} in the page header to open the item page. Fill in
Lowercase item please. This is a difficult section - is it too patronising? What else matters here? Validation maybe? Conditionally-shown fields?

2024-10-16 09:54 UTC, phazonoverload commented on content/3.content/2.editor.md
> +settings, the App will automatically open the item page when selecting said collection.
```suggestion
If the collection is configured as a [singleton](/data-modeling/collections) in the data model
settings, the App will automatically open the item page when selecting the collection.
```

2024-10-16 09:54 UTC, phazonoverload commented on content/3.content/2.editor.md
> +settings, the App will automatically open the item page when selecting said collection.
I'd also maybe add that singletons are typically used as if they were a key-value store, even if it is really a collection with only a single item?

2024-10-16 09:54 UTC, phazonoverload commented on content/3.content/2.editor.md
> +When editing an item, you can click on :icon{name="material-symbols:more-vert"} to select some advanced options, amongst them "Save as Copy". Selecting this will save said copy.
```suggestion
When editing an item, you can click on :icon{name="material-symbols:more-vert"} to select some advanced options, amongst them "Save as Copy". Selecting this will save a copy.
```

You'll notice this a bunch. I think 'a' or 'the' is almost always better than 'said', which feels a bit academic.

2024-10-16 09:54 UTC, phazonoverload commented on content/3.content/2.editor.md
> +Requires an [archive field](/data-modeling/collections) to be configured within the collection's data model
```suggestion
Archiving requires an [archive field](/data-modeling/collections) to be configured within the collection's data model
```

2024-10-16 09:54 UTC, phazonoverload commented on content/3.content/2.editor.md
> -<!-- 'soft delete' -->
Can you talk about this being like a 'soft delete'. In that, by default, it won't show up in search results or be returned by the API. But they still exist and, given the correct queries, will be accessible.

2024-10-16 09:54 UTC, phazonoverload commented on content/3.content/2.editor.md
> +To revert an item, navigate to the content module and select the desired collection and select the desired item. Click on "Revisions" in the page sidebar and then on the revision you wish to preview.
```suggestion
To revert an item, navigate to the content module and select the desired collection and select the desired item. Click on "Revisions" in the editor sidebar and then on the revision you wish to preview. Go to "Revisions Made" in the side menu and view the revision differences. Click :icon{name="material-symbols:settings-backup-restore"} to revert the item's values and return to the item page.
```

2024-10-16 09:54 UTC, phazonoverload commented on content/3.content/2.editor.md
> +You can also revert Items [programmatically via the API](/api-reference/system/revisions).
```suggestion
You can also revert items [programmatically via the API](/api-reference/system/revisions).
```

2024-10-16 09:54 UTC, phazonoverload commented on content/3.content/2.editor.md
> +You can add comments to items in the sidebar by clicking on "Comments", which will show the form for submitting one. You can use the @ button to tag specific users in said comment.
```suggestion
You can add comments to items in the sidebar by clicking on "Comments", which will show the form for submitting one. You can use the @ button to tag specific users in your comment.
```

2024-10-16 09:54 UTC, phazonoverload commented on content/3.content/3.layouts.md
> +Layouts are customized displays for viewing and interacting with the items in a collection.
Not the word displays! We use it to mean something else (I know I know - there's a bunch of words that have this characteristic, like 'action', bleh.)

2024-10-16 09:54 UTC, phazonoverload commented on content/3.content/3.layouts.md
> +::
I think this is a lot, and I think that this can probably just be prose instead of callouts. Additionally, can you use title case for callout titles please

2024-10-16 09:54 UTC, phazonoverload commented on content/3.content/3.layouts.md
> +etc.
Given short explanations - I'd do this as a table with category in left, and description in right.

2024-10-16 09:54 UTC, phazonoverload commented on content/3.content/3.layouts.md
> +</video> -->
Add a TODO so we can find it easily (as with others) an da note we'll update with images, not videos.

2024-10-16 09:54 UTC, phazonoverload commented on content/3.content/3.layouts.md
> +</video> -->
This whole page could definitely benefit from tables over lists.

2024-10-16 09:54 UTC, phazonoverload commented on content/3.content/4.import-export.md
> +The content module allows importing and exporting of multiple items stored as files.
This reads weird because of 'multiple items stored as files'. What exactly do you mean by this?

2024-10-16 09:54 UTC, phazonoverload commented on content/3.content/4.import-export.md
> +## Import Items
Please can you add more detail here. What are the requirements to import? I assume table headers need to match field names.

2024-10-16 09:54 UTC, phazonoverload commented on content/3.content/4.import-export.md
> +- **Fields** — Add, remove, and re-order the item fields that will be exported.
table

2024-10-16 09:54 UTC, phazonoverload commented on content/3.content/5.live-preview.md
> +need to refresh the browser.
```suggestion
Live preview allows you to show changes in your website collection before publishing and without the need to refresh the browser.
```

2024-10-16 09:54 UTC, phazonoverload commented on content/3.content/5.live-preview.md
> +`http://your-website-url/<field>?preview=true`
preview=true is not needed. That's a common strategy in order to use alternate logic and fetch from Directus live instead of cache/static

2024-10-16 09:54 UTC, phazonoverload commented on content/3.content/5.live-preview.md
> +
I think there needs to be more here from our convo the other day. I think maybe a brief example that if your URL is URL/posts/{id} and your id field for an item is 42, then the URL that will be loaded is URL/posts/42. You may choose to add preview=true to indicate in your client that it needs to treat this as a live preview. And you may choose to add an access token with ability to view items as a query param. 

This bit really needs a bit more imo, while staying clear of implementation-specific examples. I think the above is generic enough.

2024-10-16 09:54 UTC, phazonoverload commented on content/3.content/5.live-preview.md
> +Clicking on the "Dimensions Display" icon also lets you preview your content on desktop and mobile screens.
Maybe also mention you can pop it out

2024-10-16 09:54 UTC, phazonoverload commented on content/3.content/6.content-versioning.md
> +- version represents a set of future changes to be applied to the item.
I would do a bit more here, and I would probably also talk about it in terms of git branching - a snapshot of the item can be copied to a version for further work to happen on it. 

THEN a version represents a set of future changes etc

2024-10-16 09:54 UTC, phazonoverload commented on content/3.content/6.content-versioning.md
> +- the default version that is displayed to users. The main version is the "source of truth" for all other versions.
Remember, it isn't necessarily published - that's use case specific. I'd put that at the end and acknowledge that it is OFTEN used for the published content. I think the rest of yoru explainer - default displayed, source of truth, etc, is great.

2024-10-16 09:54 UTC, phazonoverload commented on content/3.content/6.content-versioning.md
> +Open the version you want to promote and select the "Promote Version" option from the dropdown. In the "Changes" tab, you can review all the changes made in the version and decide which changes to ac
More here - for each field you can choose to include it in the promotion or leave it. I'd add an image here too. It's a cool interface.

2024-10-16 09:54 UTC, phazonoverload commented on content/3.content/6.content-versioning.md
> +::
Can you, separately, go through all mentions of the API reference across all pages and add a TODO comment so we can make sure they'er correct.

2024-10-16 09:54 UTC, phazonoverload commented on content/3.content/6.content-versioning.md
> +unintentionally purge content versions.
This feels scary. It's important, but is there any way we can soften this?

2024-10-16 09:54 UTC, phazonoverload commented on content/3.content/6.content-versioning.md
> +unintentionally purge content versions.
This page also needs, somewhere, mention that version is a dynamic variable that can be added to the live preview URL so you can preview a specific version. And then link back maybe to live preview?

2024-10-16 09:54 UTC, phazonoverload commented on content/3.content/7.translations.md
> +language preference.
Remove first and second. Conciseness is key.

2024-10-16 09:54 UTC, phazonoverload commented on content/3.content/7.translations.md
> +::
Somewhere in this doc also talk about app translations via Crowdin and that this is different from CONTENT translations (briefly mentioned in the relationships page in data modeling.) If you need help on framing it, look at the first couple of eps of Academy.

2024-10-16 12:50 UTC, hola-soy-milk commented on content/3.content/7.translations.md
> +::
@phazonoverload Should I include a full walkthrough on contributing to CrowdIn?

I didn't find a mention of CrowdIn in the relationships page.

2024-10-16 13:45 UTC, phazonoverload commented on content/3.content/7.translations.md
> +::
No the relationships page is about content translations. But that's obviously important in a content section. 

Maybe something like: 

> Many parts of the Data Studio are already translated into x many languages via community contribution on Crowdin. 
>
> ## Translation Strings
>
> ## Content Translations

2024-10-17 13:25 UTC, hola-soy-milk commented
Thanks for the review! I think I've caught everything here. Can you please take another look?

2024-10-17 13:29 UTC, phazonoverload commented on content/3.content/1.explore.md
> +In order to be grouped into the `AND` or `OR` groups, filters must be indented into them.
```suggestion
In order for filters to be included in `AND` or `OR` groups, filters must be indented below them in the filter UI.
```

2024-10-17 13:40 UTC, phazonoverload commented on content/3.content/4.import-export.md
> +## Import Items
This bit is outstanding

2024-10-17 13:40 UTC, phazonoverload commented on content/3.content/5.live-preview.md
> +Once configured, Directus will send a request to your application for a page with the specified URL format. For example, if you've configured it to be `/posts/{id}`, and load the preview for the item
```suggestion
Once configured, Directus will send a request to your application for a page with the specified URL format. For example, if you've configured the URL to be `https://mysite.com/posts/{id}`, and load the preview for the item with the an `id` of `42`, then your application will receive a request to `https://mysite.com/posts/42`. You may choose to add `preview=true` to indicate to your client that it needs to treat this as a live preview. You may also choose to add an access token with the ability to view items as an additional URL query parameter.
```

2024-10-17 13:40 UTC, phazonoverload commented on content/3.content/6.content-versioning.md
> +- version represents a set of future changes to be applied to the item.
This is outstanding

2024-10-17 13:42 UTC, hola-soy-milk commented on content/3.content/4.import-export.md
> +## Import Items
Oh you know what, I put it above the section. That''s on me. Will fix shortly

2024-10-18 06:20 UTC, phazonoverload commented on content/3.content/4.import-export.md
> +Note that the fields in the file you import must match the field IDs of the item fields of the collection you're importing into. These will otherwise be skipped.
```suggestion
The field headers in the imported file must match the field keys of the collection you're importing into. Otherwise, the column will be skipped.
```

2024-10-18 06:21 UTC, phazonoverload commented on content/3.content/6.content-versioning.md
> +- **Version**: A version of an item is a snapshot that gets copied from the current or "main" item, allowing you to safely make changes and later promote to be the main version. Any changes to the ma
```suggestion
- **Version**: A version of an item is a snapshot that gets copied from the current or `main` version, allowing you to safely make changes and later promote to be the main version. Any changes to the main version made in the meantime are updated automatically.
```

2024-10-18 08:45 UTC, phazonoverload commented on content/3.content/7.translations.md
> +Once this field is added to a collection, a few new collections will be created. One being a pre-populated `languages` collection, as well as an invisible `<colletion-name>_translations`.
```suggestion
Once this field is added to a collection, a few new collections will be created. One being a pre-populated `languages` collection, as well as a hidden `<colletion-name>_translations` collection.
```

2024-10-18 08:46 UTC, phazonoverload commented on content/3.content/7.translations.md
> +description: Translation Strings enable you to translate things like dropdown options, placeholder text, field notes, and more.
```suggestion
description: Both content and the data studio can be translated into multiple languages. 
```

2024-10-18 08:46 UTC, phazonoverload approved these changes

2024-10-18 08:46 UTC, merged