Writeup SSO pages
directus/docs pull request #38
Opened 2024-10-11 10:52 UTC by hola-soy-milk

2024-10-15 12:13 UTC, phazonoverload requested changes
Good start. Very similar feedback throughout - pronouns are weird, lots of redundant sentence starters, and a desire to use tabs for equivalent examples with the API/SDK (although elsewhere in the docs we just show the REST examples - look at the 2FA page - maybe we do the same here?).

2024-10-15 12:13 UTC, phazonoverload commented on content/4.auth/7.sso/1.index.md
> +systems.
```suggestion
Single Sign-On (SSO) is a mechanism which allows to use external providers to login into systems. For example, you can use
your Google or Facebook account to authenticate without the need to create a new registration.
```

Felt a bit wordy

2024-10-15 12:13 UTC, phazonoverload commented on content/4.auth/7.sso/1.index.md
> +Directus supports four standard types of SSO mechanisms:
```suggestion
Directus supports four SSO mechanisms:
```

2024-10-15 12:13 UTC, phazonoverload commented on content/4.auth/7.sso/1.index.md
> +Here are the configurations allowed for each one: [SSO configuration](/configuration/auth-sso)
Make this a callout type link

2024-10-15 12:13 UTC, phazonoverload commented on content/4.auth/7.sso/1.index.md
> +In order to use these mechanisms you need to create an application/configuration on your preferred external provider, set the environment variables to configure the external provider and optionally,
```suggestion
In order to use these mechanisms you need to create an application/configuration on your preferred external provider, set the environment variables to configure the external provider and, optionally, set the environment variables to configure cookies.
```

2024-10-15 12:13 UTC, phazonoverload commented on content/4.auth/7.sso/1.index.md
> +## SSO with Directus behind Proxy
```suggestion
## SSO with Directus Behind a Proxy
```

2024-10-15 12:13 UTC, phazonoverload commented on content/4.auth/7.sso/1.index.md
> +In this quick guide, we'll show how to set up the `global-agent` package by extending the Directus Docker Image.
```suggestion
In this guide, you'll learn how to set up the `global-agent` package by extending the Directus Docker Image.
```

you/yours, not we/ours for docs

2024-10-15 12:13 UTC, phazonoverload commented on content/4.auth/7.sso/1.index.md
> +First, create a patch file to adjust the `pm2` configuration file so that `global-agent` is registered at startup:
```suggestion
Create a patch file to adjust the `pm2` configuration file so that `global-agent` is registered at startup:
```

2024-10-15 12:13 UTC, phazonoverload commented on content/4.auth/7.sso/1.index.md
> +`global-agent` package and apply the previously created patch file:
```suggestion
In the same directory, create a `Dockerfile`. Extend the Directus Image, install the
`global-agent` package, and apply the previously created patch file:
```

Remove these filler words at the start, like 'first', 'next', etc. Always remain concise by just giving instruction instead of prefacing each sentence. Also we love an Oxford comma.

2024-10-15 12:13 UTC, phazonoverload commented on content/4.auth/7.sso/1.index.md
> +FROM directus/directus:{{ packages.directus.version.major }}.x.y
This dynamic variable was in the old docs but I don't think it's available (yet) in the new docs. Hardcode the value and then make a note after the snippet.

2024-10-15 12:13 UTC, phazonoverload commented on content/4.auth/7.sso/1.index.md
>  <ListChildren />
Replace this with an explicit link please

2024-10-15 12:13 UTC, phazonoverload commented on content/4.auth/7.sso/2.seamless.md
>  # Seamless SSO
Description please

2024-10-15 12:13 UTC, phazonoverload commented on content/4.auth/7.sso/2.seamless.md
> +required to work across domains.
```suggestion
While sometimes you want your users to directly have access to the Directus project, in other cases you may need to
fetch private data from Directus in your application using external providers. 
```

> For such cases, a special configuration is required to work across domains.

This is implied.

2024-10-15 12:13 UTC, phazonoverload commented on content/4.auth/7.sso/2.seamless.md
> +Setup an external provider. You'll find some examples further down below. Allow the cookie to be accessible across domains. There are two authentication mechanisms for this.
```suggestion
Set up an external provider. You'll find some examples further down below. Allow the cookie to be accessible across domains. There are two authentication mechanisms for this.
```

I'm not too sure about this opener. I don't think it's clear.

2024-10-15 12:13 UTC, phazonoverload commented on content/4.auth/7.sso/2.seamless.md
> +**Authentication Mode: cookie (legacy)**
If it's legacy, I'd vote we remove it?

2024-10-15 12:13 UTC, phazonoverload commented on content/4.auth/7.sso/2.seamless.md
> +
```suggestion
Replace `https://directus.myserver.com` with the address of your Directus instance, while `https://client.myserver.com/login` should be the address of your client application. The `/login` path is not necessary, but helps to separate concerns.

```

Another example of sentence redundant openers

2024-10-15 12:13 UTC, phazonoverload commented on content/4.auth/7.sso/2.seamless.md
> +
Whichever snippets are kept - whether we remove cookie or not - put this in a code tab. Look at the authentication partial for an example.

2024-10-15 12:13 UTC, phazonoverload commented on content/4.auth/7.sso/2.seamless.md
> +::callout{type="warning" title="Disabling secured cookies"}
```suggestion
::callout{type="warning" title="Disabling Secured Cookies"}
```

2024-10-15 12:14 UTC, hola-soy-milk commented on content/4.auth/7.sso/2.seamless.md
> +**Authentication Mode: cookie (legacy)**
I'm so glad you agree, gonna joyfully remove

2024-10-15 12:25 UTC, hola-soy-milk commented on content/4.auth/7.sso/1.index.md
>  <ListChildren />
This being the `ListChildren` component?

2024-10-15 12:32 UTC, hola-soy-milk commented on content/4.auth/7.sso/1.index.md
>  <ListChildren />
Because if so, we have the "Next page" links below that would do the same

2024-10-15 12:42 UTC, hola-soy-milk commented
Should be sorted, thanks for the review! Could you please take another look?

2024-10-16 10:19 UTC, phazonoverload commented on content/4.auth/7.sso/1.index.md
> +Find out what the configurations for each SSO configuration are.
```suggestion
Check out specific the SSO configuration variables for different mechanisms.
```

2024-10-16 10:19 UTC, phazonoverload commented on content/4.auth/7.sso/1.index.md
> +Check out specific the SSO configuration variables for different mechanisms.
```suggestion
Check out specific SSO configuration variables for different mechanisms.
```

2024-10-16 10:20 UTC, phazonoverload commented on content/4.auth/7.sso/1.index.md
> +## Supported SSO mechanisms
```suggestion
## Supported SSO Mechanisms
```

2024-10-16 10:20 UTC, phazonoverload commented on content/4.auth/7.sso/2.seamless.md
> +## Testing Seamless SSO locally
```suggestion
## Testing Seamless SSO Locally
```

2024-10-16 10:20 UTC, phazonoverload approved these changes
LGTM

2024-10-16 10:23 UTC, phazonoverload commented on content/4.auth/7.sso/2.seamless.md
> +Note that no `REFRESH_TOKEN_COOKIE_DOMAIN` or `SESSION_COOKIE_DOMAIN` value is set.
````suggestion
Locally, Directus won't be served under
a valid SSL certificate, which is a requirement for "Secure" cookies. Instead, for local testing purposes (and local
testing purposes only), the following configuration can be used when using session authentication:

```sh
SESSION_COOKIE_SECURE="false"
SESSION_COOKIE_SAME_SITE="lax"

```
Note that no  `SESSION_COOKIE_DOMAIN` value is set.
````

2024-10-16 10:29 UTC, merged